### ISSUE TITLE
catkin_make Franka Ros

### ISSUE THREAD

**Issue by vitomillan** [frankaemika/franka_ros#10]
Beim kompilieren von Franka-Ros 

`~/catkin_ws$ catkin_make -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=~/libfranka/build`

tritt folgender Fehler auf:

> In function `main':
franka_joint_state_publisher.cpp:(.text.startup+0x5a0): undefined reference to `franka::Robot::Robot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, franka::RealtimeConfig)'
collect2: error: ld returned 1 exit status

`
Base path: /home/mti/catkin_ws
Source space: /home/mti/catkin_ws/src
Build space: /home/mti/catkin_ws/build
Devel space: /home/mti/catkin_ws/devel
Install space: /home/mti/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/mti/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/mti/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.8
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 9 packages in topological order:
-- ~~  - franka_description
-- ~~  - franka_ros (metapackage)
-- ~~  - franka_msgs
-- ~~  - franka_visualization
-- ~~  - franka_gripper
-- ~~  - franka_hw
-- ~~  - franka_control
-- ~~  - franka_example_controllers
-- ~~  - panda_moveit_config
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'franka_description'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_description)
-- +++ processing catkin metapackage: 'franka_ros'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_ros)
-- +++ processing catkin package: 'franka_msgs'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- franka_msgs: 2 messages, 0 services
-- +++ processing catkin package: 'franka_visualization'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_visualization)
-- +++ processing catkin package: 'franka_gripper'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_gripper)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action franka_gripper/Grasp /home/mti/catkin_ws/src/franka_ros-kinetic-devel/franka_gripper/action/Grasp.action
-- Generating .msg files for action franka_gripper/Homing /home/mti/catkin_ws/src/franka_ros-kinetic-devel/franka_gripper/action/Homing.action
-- Generating .msg files for action franka_gripper/Stop /home/mti/catkin_ws/src/franka_ros-kinetic-devel/franka_gripper/action/Stop.action
-- Generating .msg files for action franka_gripper/Move /home/mti/catkin_ws/src/franka_ros-kinetic-devel/franka_gripper/action/Move.action
-- franka_gripper: 28 messages, 0 services
-- +++ processing catkin package: 'franka_hw'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_hw)
-- +++ processing catkin package: 'franka_control'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_control)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action franka_control/ErrorRecovery /home/mti/catkin_ws/src/franka_ros-kinetic-devel/franka_control/action/ErrorRecovery.action
-- franka_control: 7 messages, 7 services
-- +++ processing catkin package: 'franka_example_controllers'
-- ==> add_subdirectory(franka_ros-kinetic-devel/franka_example_controllers)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- franka_example_controllers: 1 messages, 0 services
-- +++ processing catkin package: 'panda_moveit_config'
-- ==> add_subdirectory(franka_ros-kinetic-devel/panda_moveit_config)
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mti/catkin_ws/build
####
####
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target _franka_msgs_generate_messages_check_deps_Errors
[  0%] Built target _franka_msgs_generate_messages_check_deps_FrankaState
[  0%] Built target roscpp_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_lisp
[  0%] Built target rosgraph_msgs_generate_messages_nodejs
[  0%] Built target geometry_msgs_generate_messages_py
[  0%] Built target geometry_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_lisp
[  0%] Built target sensor_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_cpp
[  0%] Built target geometry_msgs_generate_messages_cpp
[  0%] Built target sensor_msgs_generate_messages_eus
[  0%] Built target sensor_msgs_generate_messages_nodejs
[  0%] Built target roscpp_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_eus
[  0%] Built target roscpp_generate_messages_eus
[  0%] Built target rosgraph_msgs_generate_messages_py
[  0%] Built target rosgraph_msgs_generate_messages_lisp
[  0%] Built target roscpp_generate_messages_nodejs
[  0%] Built target actionlib_msgs_generate_messages_cpp
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveActionResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopAction
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopActionFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveActionFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingAction
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspAction
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingActionResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopActionGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveActionGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspActionResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopActionResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_MoveAction
[  0%] Built target actionlib_msgs_generate_messages_nodejs
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingActionGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspActionFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspActionGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspResult
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_HomingActionFeedback
[  0%] Built target _franka_gripper_generate_messages_check_deps_GraspGoal
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopResult
[  0%] Built target actionlib_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_eus
[  0%] Built target _franka_gripper_generate_messages_check_deps_StopGoal
[  0%] Built target trajectory_msgs_generate_messages_nodejs
[  0%] Built target trajectory_msgs_generate_messages_py
[  0%] Built target trajectory_msgs_generate_messages_cpp
[  0%] Built target trajectory_msgs_generate_messages_eus
[  0%] Built target control_msgs_generate_messages_nodejs
[  0%] Built target actionlib_generate_messages_py
[  0%] Built target actionlib_generate_messages_cpp
[  0%] Built target trajectory_msgs_generate_messages_lisp
[  0%] Built target control_msgs_generate_messages_lisp
[  0%] Built target actionlib_msgs_generate_messages_py
[  0%] Built target actionlib_generate_messages_lisp
[  0%] Built target control_msgs_generate_messages_eus
[  0%] Built target control_msgs_generate_messages_py
[  0%] Built target control_msgs_generate_messages_cpp
[ 11%] Built target franka_gripper_generate_messages_py
Scanning dependencies of target franka_hw
[ 11%] Built target actionlib_generate_messages_nodejs
[ 15%] Built target actionlib_generate_messages_eus
[ 22%] Built target franka_gripper_generate_messages_cpp
[ 22%] Building CXX object franka_ros-kinetic-devel/franka_hw/CMakeFiles/franka_hw.dir/src/control_mode.cpp.o
[ 22%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryAction
[ 22%] Built target _franka_control_generate_messages_check_deps_SetLoad
[ 22%] Built target _franka_control_generate_messages_check_deps_SetForceTorqueCollisionBehavior
[ 22%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryActionResult
[ 22%] Built target _franka_control_generate_messages_check_deps_SetCartesianImpedance
[ 22%] Built target _franka_control_generate_messages_check_deps_SetEEFrame
[ 23%] Building CXX object franka_ros-kinetic-devel/franka_hw/CMakeFiles/franka_hw.dir/src/franka_hw.cpp.o
[ 23%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryResult
[ 23%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryGoal
[ 23%] Built target _franka_control_generate_messages_check_deps_SetFullCollisionBehavior
[ 23%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryActionFeedback
[ 23%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryFeedback
[ 23%] Built target _franka_control_generate_messages_check_deps_SetKFrame
[ 23%] Built target _franka_control_generate_messages_check_deps_ErrorRecoveryActionGoal
[ 23%] Built target _franka_control_generate_messages_check_deps_SetJointImpedance
[ 23%] Built target _catkin_empty_exported_target
[ 23%] Built target tf2_msgs_generate_messages_eus
[ 23%] Built target controller_manager_msgs_generate_messages_cpp
[ 23%] Built target tf2_msgs_generate_messages_lisp
[ 23%] Built target tf2_msgs_generate_messages_nodejs
[ 23%] Built target tf_generate_messages_py
[ 23%] Built target controller_manager_msgs_generate_messages_eus
[ 23%] Building CXX object franka_ros-kinetic-devel/franka_hw/CMakeFiles/franka_hw.dir/src/resource_helpers.cpp.o
[ 23%] Built target tf2_msgs_generate_messages_cpp
[ 23%] Built target controller_manager_msgs_generate_messages_py
[ 23%] Built target tf_generate_messages_nodejs
[ 23%] Built target controller_manager_msgs_generate_messages_nodejs
[ 23%] Built target tf_generate_messages_cpp
[ 23%] Built target controller_manager_msgs_generate_messages_lisp
[ 23%] Built target tf2_msgs_generate_messages_py
[ 23%] Built target tf_generate_messages_lisp
[ 23%] Built target tf_generate_messages_eus
[ 23%] Built target _franka_example_controllers_generate_messages_check_deps_JointTorqueComparison
[ 24%] Built target franka_example_controllers_gencfg
[ 24%] Building CXX object franka_ros-kinetic-devel/franka_hw/CMakeFiles/franka_hw.dir/src/trigger_rate.cpp.o
[ 24%] Built target dynamic_reconfigure_gencfg
[ 24%] Built target dynamic_reconfigure_generate_messages_cpp
[ 24%] Built target dynamic_reconfigure_generate_messages_nodejs
[ 24%] Built target dynamic_reconfigure_generate_messages_eus
[ 24%] Built target dynamic_reconfigure_generate_messages_lisp
[ 24%] Built target dynamic_reconfigure_generate_messages_py
[ 24%] Built target franka_msgs_generate_messages_lisp
[ 25%] Built target franka_msgs_generate_messages_py
[ 26%] Built target franka_msgs_generate_messages_cpp
[ 27%] Built target franka_msgs_generate_messages_eus
[ 28%] Built target franka_msgs_generate_messages_nodejs
Scanning dependencies of target franka_joint_state_publisher
[ 28%] Building CXX object franka_ros-kinetic-devel/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/src/franka_joint_state_publisher.cpp.o
[ 39%] Built target franka_gripper_generate_messages_nodejs
[ 49%] Built target franka_gripper_generate_messages_lisp
[ 60%] Built target franka_gripper_generate_messages_eus
[ 67%] Built target franka_control_generate_messages_py
[ 73%] Built target franka_control_generate_messages_nodejs
[ 78%] Built target franka_control_generate_messages_cpp
Scanning dependencies of target franka_control_generate_messages_eus
[ 78%] Generating EusLisp code from franka_control/ErrorRecoveryResult.msg
[ 78%] Generating EusLisp code from franka_control/ErrorRecoveryActionResult.msg
[ 79%] Generating EusLisp code from franka_control/ErrorRecoveryAction.msg
[ 79%] Generating EusLisp code from franka_control/ErrorRecoveryGoal.msg
[ 80%] Generating EusLisp code from franka_control/ErrorRecoveryActionFeedback.msg
[ 80%] Generating EusLisp code from franka_control/ErrorRecoveryFeedback.msg
[ 80%] Generating EusLisp code from franka_control/ErrorRecoveryActionGoal.msg
[ 81%] Generating EusLisp code from franka_control/SetCartesianImpedance.srv
[ 81%] Generating EusLisp code from franka_control/SetEEFrame.srv
[ 81%] Generating EusLisp code from franka_control/SetForceTorqueCollisionBehavior.srv
Scanning dependencies of target franka_control_generate_messages_lisp
[ 82%] Generating Lisp code from franka_control/ErrorRecoveryResult.msg
[ 83%] Generating EusLisp code from franka_control/SetJointImpedance.srv
[ 83%] Generating Lisp code from franka_control/ErrorRecoveryActionResult.msg
[ 83%] Generating EusLisp code from franka_control/SetFullCollisionBehavior.srv
[ 83%] Generating Lisp code from franka_control/ErrorRecoveryAction.msg
[ 84%] Generating EusLisp code from franka_control/SetLoad.srv
[ 85%] Generating Lisp code from franka_control/ErrorRecoveryGoal.msg
[ 85%] Generating EusLisp code from franka_control/SetKFrame.srv
[ 85%] Generating Lisp code from franka_control/ErrorRecoveryActionFeedback.msg
[ 85%] Generating EusLisp manifest code for franka_control
[ 85%] Generating Lisp code from franka_control/ErrorRecoveryFeedback.msg
[ 86%] Generating Lisp code from franka_control/ErrorRecoveryActionGoal.msg
[ 86%] Generating Lisp code from franka_control/SetCartesianImpedance.srv
[ 87%] Generating Lisp code from franka_control/SetEEFrame.srv
[ 87%] Generating Lisp code from franka_control/SetForceTorqueCollisionBehavior.srv
[ 87%] Generating Lisp code from franka_control/SetJointImpedance.srv
[ 88%] Generating Lisp code from franka_control/SetFullCollisionBehavior.srv
[ 88%] Generating Lisp code from franka_control/SetLoad.srv
[ 88%] Generating Lisp code from franka_control/SetKFrame.srv
[ 88%] Built target franka_control_generate_messages_eus
Scanning dependencies of target franka_example_controllers_generate_messages_nodejs
[ 88%] Generating Javascript code from franka_example_controllers/JointTorqueComparison.msg
[ 88%] Built target franka_control_generate_messages_lisp
Scanning dependencies of target franka_example_controllers_generate_messages_cpp
[ 88%] Generating C++ code from franka_example_controllers/JointTorqueComparison.msg
[ 88%] Built target franka_example_controllers_generate_messages_nodejs
Scanning dependencies of target franka_example_controllers_generate_messages_py
[ 88%] Generating Python from MSG franka_example_controllers/JointTorqueComparison
[ 89%] Linking CXX executable /home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher
[ 89%] Built target franka_example_controllers_generate_messages_cpp
Scanning dependencies of target franka_example_controllers_generate_messages_eus
[ 90%] Generating EusLisp code from franka_example_controllers/JointTorqueComparison.msg
[ 90%] Generating EusLisp manifest code for franka_example_controllers
[ 91%] Generating Python msg __init__.py for franka_example_controllers
CMakeFiles/franka_joint_state_publisher.dir/src/franka_joint_state_publisher.cpp.o: In function `main':
franka_joint_state_publisher.cpp:(.text.startup+0x5a0): undefined reference to `franka::Robot::Robot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, franka::RealtimeConfig)'
collect2: error: ld returned 1 exit status
franka_ros-kinetic-devel/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/build.make:114: recipe for target '/home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher' failed
make[2]: *** [/home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher] Error 1
CMakeFiles/Makefile2:1166: recipe for target 'franka_ros-kinetic-devel/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/all' failed
make[1]: *** [franka_ros-kinetic-devel/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 91%] Built target franka_example_controllers_generate_messages_py
[ 91%] Built target franka_example_controllers_generate_messages_eus
[ 92%] Linking CXX shared library /home/mti/catkin_ws/devel/lib/libfranka_hw.so
[ 92%] Built target franka_hw
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`

**Comment by fwalch** [comment]
Dieser Fehler tritt auf, wenn eine alte Version von `ros-kinetic-libfranka` installiert ist. Nach der Deinstallation (`sudo apt remove ros-kinetic-libfranka`) sollte das Kompilieren von `franka_ros` funktionieren. Wir werden aber auch versuchen, das zugrundeliegende Problem zu beheben, sodass es nicht mehr zu solchen Konflikten kommt.

**Comment by vitomillan** [comment]
Es scheint leider eine andere Ursache zu haben. Libfranka und ros-kinetic-libfranka und der panda-server sollten bereits die aktuellste Version haben.

`
catkin_make -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=/libfranka/build -j 1`

liefert ebenfalls folgenden Fehler:

`[  5%] Linking CXX executable /home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher
CMakeFiles/franka_joint_state_publisher.dir/src/franka_joint_state_publisher.cpp.o: In Funktion `main':
franka_joint_state_publisher.cpp:(.text.startup+0x5a0): Nicht definierter Verweis auf `franka::Robot::Robot(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, franka::RealtimeConfig)'
collect2: error: ld returned 1 exit status
franka_ros/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/build.make:114: die Regel für Ziel „/home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher“ scheiterte
make[2]: *** [/home/mti/catkin_ws/devel/lib/franka_visualization/franka_joint_state_publisher] Fehler 1
CMakeFiles/Makefile2:1166: die Regel für Ziel „franka_ros/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/all“ scheiterte
make[1]: *** [franka_ros/franka_visualization/CMakeFiles/franka_joint_state_publisher.dir/all] Fehler 2
Makefile:138: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
Invoking "make -j 1" failed
`

**Comment by fwalch** [comment]
>  Libfranka und ros-kinetic-libfranka und der panda-server sollten bereits die aktuellste Version haben.

Die aktuellste Version von `libfranka` ist noch gar nicht in den ROS-Repos vorhanden; die alte Version muss unbedingt deinstalliert werden, damit die Kompilierung funktioniert. Haben Sie `sudo apt remove ros-kinetic-libfranka` ausgeführt? Haben Sie vielleicht eine andere Version von `libfranka` installiert (`sudo apt remove libfranka`)?

**Comment by vitomillan** [comment]
Danke für den Hinweis. Dass die libfranka in den ROS-Repos noch nicht aktuell ist, ist einem Kollegen dann später auch aufgefallen. Letztlich wurden alle Dateien der älteren Version manuell vom System entfernt und dann erfolgreich kompiliert.

Besten Dank!
