### ISSUE TITLE
Release into ROS Noetic?

### ISSUE THREAD

**Issue by davetcoleman** [frankaemika/franka_ros#104]
ROS 1 Noetic is released and the MoveIt project is working on migrating to this new LTS (and last version of ROS 1)

So that the MoveIt tutorials with the Panda still work, can you all test your repo on Noetic and consider making a ``noetic-devel`` branch? Thanks!

**Comment by davetcoleman** [comment]
In particular, we are seeing the following error, even when we install this package for source on Noetic:

> franka_gripper: Cannot locate rosdep definition for [libfranka]

**Comment by rhaschke** [comment]
Actually, we only need franka_description to be released for MoveIt. Would be great, if somebody could handle this soon.

**Comment by tylerjw** [comment]
One more :+1: for a Noetic release.  We need it released for us to be able to release MoveIt for Noetic.

**Comment by davetcoleman** [comment]
I just emailed Sebastian and Florian at Franka

**Comment by tylerjw** [comment]
Looks like this was done, and is now in our court so franka can release the rest of their packages.

**Comment by davetcoleman** [comment]
@tylerjw i believe this particular issue can be closed now, correct?

**Comment by tylerjw** [comment]
yes, someone with permissions on this repo has to close the issue.
