### ISSUE TITLE
Visual issue gazebo

### ISSUE THREAD

**Issue by FloArel** [frankaemika/franka_ros#111]
Hello everyone,

I'm trying to use the arm on a RMP rover, but there is a visual issue. 
When i pull the project and launch it, everything is fine, I can see the arm. But when I include the urdf in my project it's not working anymore. The fact is that even if i can't see it, the arm is here: when i use the collision view, here it is. And the joint are also loaded in gazebo (see photos).
I think the issue comes from the dae files because when i use others ones that i have, i can see them in gazebo.
Someone knows how to figure it out or explains me why it's happening ?

![emptyissue](https://user-images.githubusercontent.com/56632965/90512805-ff9ee400-e15e-11ea-8241-d7d46d4db6a3.png)
![gazebocollision](https://user-images.githubusercontent.com/56632965/90513010-51476e80-e15f-11ea-8f34-dc6f2aa982c9.png)
Here is a picture of my modifications in the arm's urdf: 
![urdf](https://user-images.githubusercontent.com/56632965/90513362-d03ca700-e15f-11ea-8ba8-0095ef061c09.png)
I included my the arm in my own urdf with these commands :

    <xacro:include filename="$(find franka_description)/robots/panda_arm.urdf.xacro"/>
     
    <xacro:panda_arm/>

Thanks !

**Comment by sabaghian** [comment]
Our new release contains an integrated Gazebo Simulation.
