### ISSUE TITLE
ROS 2 support

### ISSUE THREAD

**Issue by mahaarbo** [frankaemika/franka_ros#117]
I am currently trying to port the `franka_ros` package to ROS 2, and have managed to get `franka_msgs` and `franka_description`, and most of `franka_gripper` so far.  
Are there any plans for ROS 2 support? Is anyone else working on this as well?

**Comment by gavanderhoorn** [comment]
This driver is heavily dependent on `ros_control`, so a port would logically also depend on `ros2_control`. That's in-progress, but not finished yet.

Without that, I believe it's going to be difficult to get things to work in ROS 2.

**Comment by mahaarbo** [comment]
Yup, that's where things stopped for me. But `ros2_control` is starting to take shape, so I think development alongside it can be interesting to do. If there is little to be discussed on this point now, I can close the issue.

**Comment by gavanderhoorn** [comment]
> If there is little to be discussed on this point now, I can close the issue.

Just a clarification (if needed): I'm not a maintainer nor a dev here. I just wanted to point out what I believe to be the main blocker right now.

As to whether a ROS 2 port makes sense or is desirable: that would be up to Franka Emika (@fwalch et al.)

**Comment by DLu** [comment]
`ros2_control` seems to be in better shape. I move that we re-open this.

**Comment by mahaarbo** [comment]
As far as I can tell, when switching modes in the controller (e.g. going from joint-position level control to torque control), we must switch which callback function is bound to `libfranka`'s `robot` object ([franka_hw.cpp#L399](https://github.com/frankaemika/franka_ros/blob/kinetic-devel/franka_hw/src/franka_hw.cpp#L399)). Currently `ros2_control` does not notify the hardware interface about which command resource has been claimed (See: [ros2_control_demos#59](https://github.com/ros-controls/ros2_control_demos/issues/59), [ros2_control_demos#61](https://github.com/ros-controls/ros2_control_demos/pull/61)). 
How to best notify the `hardware_interface` that a new command resource has been claimed by a controller, and preparing for and switching is currently being developed and discussed at  [ros-controls/roadmap#41](https://github.com/ros-controls/roadmap/pull/41), and [ros-controls/roadmap#42](https://github.com/ros-controls/roadmap/pull/42). When this is finalized it should be possible to move to `ros2_control`.

**Comment by mahaarbo** [comment]
I've started a [port](https://github.com/mahaarbo/franka_ros/tree/foxy-devel) of `franka_ros` to ROS2 foxy.
Since the structure of the controller manager is different this time around, it works similarly to the `FrankaCombinableHW` with the `robot.control` loop being set up in a separate thread. The implementation works, but since the `ros2_control` thread and the `robot.control` threads are not synchronized the motion is not smooth. 

Example of how to run the code is given in the repository. Currently there is a functioning hardware interface, switching of control modes, gripper action server, and `franka_visualization` works.

Any help from Franka or the community would be appreciated!

**Comment by sabaghian** [comment]
Thank you for your input. We also think that ROS2 is starting to take shape. We have started looking into it and will announce in community as soon as the first release is ready.

**Comment by marcbone** [comment]
Christmas is early this year. Head over to [https://github.com/frankaemika/franka_ros2 ](https://github.com/frankaemika/franka_ros2) and try out the first beta version of franka_ros2!
