### ISSUE TITLE
Release 0.7.0 for ROS Melodic

### ISSUE THREAD

**Issue by simonbogh** [frankaemika/franka_ros#119]
Hi,

Will release 0.7.0 be pushed to ROS deb? Currently, I only get 0.6.0 on Melodic and e.g. `safety_distance` in the `franka_description` is not available and you get the following error when trying to instantiate the dual-arm example or load the robot arm to your own simulation with the new parameters.

    Invalid parameter "safety_distance"

**Comment by sgabl** [comment]
Hi, just released `0.7.1` and created a [PR](https://github.com/ros/rosdistro/pull/27097) - packets should be available in a few weeks.

**Comment by simonbogh** [comment]
Thanks. Will there be a release for Noetic as well?

**Comment by sgabl** [comment]
As soon as https://github.com/ros-planning/panda_moveit_config/issues/72 is done, we will release `franka_ros` fully for ROS Noetic.

**Comment by yijionglin** [comment]
Hi @sgabl ,

Could you please take a look at the comment I posted [here](https://github.com/ros-planning/panda_moveit_config/issues/72)?

Or could you please let me know if franka_ros has been fully released for ROS Noetic (all functions can be accessed like the ones in Kinetic and Melodic)?

Any idea would be highly appreciated!
