### ISSUE TITLE
franka_ros controllers crashing 

### ISSUE THREAD

**Issue by QingkaiLu** [frankaemika/franka_ros#120]
1. I am able to 

- ping the control box ( `sudo ping 172.16.0.2 -i 0.001 -D -c 10000 -s 1200`)
![image](https://user-images.githubusercontent.com/4324519/102948108-f362c480-4479-11eb-8921-b96b9da92aa5.png)

- run the communication_test example of libfranka with one warning (`./communication_test 172.16.0.2`)
![image](https://user-images.githubusercontent.com/4324519/102948287-7ab03800-447a-11eb-9a04-b41a6647697f.png)

- show the robot state using the echo_robot_state example of libfranka (`./echo_robot_state 172.16.0.2`)
![image](https://user-images.githubusercontent.com/4324519/102948364-b3501180-447a-11eb-8033-eaf18a6f5249.png)

- move the robot using the generate_joint_position_motion example of libfranka (`./generate_joint_position_motion 172.16.0.2 `)
![image](https://user-images.githubusercontent.com/4324519/102949335-e72c3680-447c-11eb-9fe9-76c560273d52.png)

- show the robot in rviz using franka_visualization of franka_ros (`roslaunch franka_visualization franka_visualization.launch robot_ip:=172.16.0.2 load_gripper:=true`)
![image](https://user-images.githubusercontent.com/4324519/102948835-aa137480-447b-11eb-8a24-2f582b8074f6.png)

2. But when I run franka_ros controller examples, they crash with the warning and errors below:
    > [WARN] [1608682350.969372]: Controller Spawner couldn't find the expected controller_manager ROS interface.
    [ERROR] [1608682380.427056883]: FrankaHW: Failed to initialize libfranka robot. libfranka: Connection timeout
    [ERROR] [1608682380.431456846]: franka_control_node: Failed to initialize FrankaHW class. Shutting down!
    
    Please see these five images below for the detailed outputs of running the franka_ros position controller example( `roslaunch franka_example_controllers joint_position_example_controller.launch robot_ip:=171.16.0.2 load_gripper:=true`):

    ![image](https://user-images.githubusercontent.com/4324519/102948986-09718480-447c-11eb-914d-314d03ddd348.png)
    ![image](https://user-images.githubusercontent.com/4324519/102946620-13908480-4476-11eb-9e10-e4965e3f939e.png)
    ![image](https://user-images.githubusercontent.com/4324519/102946699-3c187e80-4476-11eb-9016-d32f16b81304.png)
    ![image](https://user-images.githubusercontent.com/4324519/102946728-58b4b680-4476-11eb-9d43-b3af946ab5ad.png)
    ![image](https://user-images.githubusercontent.com/4324519/102946762-6e29e080-4476-11eb-87e9-615f31255a24.png)

3. System and software information:
    **panda system:** 4.0.4
    <img width="1206" alt="ScreenShot2020-12-22at4 15 20PM" src="https://user-images.githubusercontent.com/4324519/102947798-032dd900-4479-11eb-908f-680d4dbb6258.png">

    **panda FCI** is installed
    <img width="1133" alt="ScreenShot2020-12-22at4 15 37PM" src="https://user-images.githubusercontent.com/4324519/102947926-615abc00-4479-11eb-94bb-c132b9c8f173.png">

    **linux real time kernel:** 
    
    > Linux baiduusit-ThinkPad-P50 5.4.10-rt4 #1 SMP PREEMPT_RT Fri Dec 18 17:06:56 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
    
    **libfranka:** 0.8.0 installed from source
    **franka_ros:** melodic-devel branch installed from source
    **ros:** melodic

**Comment by zhengshuai1** [comment]
hi, as NVIDIA binary drivers are not supported on PREEMPT_RT kernels, do you know how to make drivers compatible with real-time kernels?

**Comment by QingkaiLu** [comment]
> hi, as NVIDIA binary drivers are not supported on PREEMPT_RT kernels, do you know how to make drivers compatible with real-time kernels?

You can use one real time kernel machine without Nvidia drivers for control and use another machine with Nvidia drivers for perception. You can connect the control and perception computer using ROS. BTW, you should create a separate git issue for your question since I don't think it is related with my issue.

**Comment by zhengshuai1** [comment]
> > hi, as NVIDIA binary drivers are not supported on PREEMPT_RT kernels, do you know how to make drivers compatible with real-time kernels?
> 
> You can use one real time kernel machine without Nvidia drivers for control and use another machine with Nvidia drivers for perception. You can connect the control and perception computer using ROS. BTW, you should create a separate git issue for your question since I don't think it is related with my issue.

thanks, I have met the same controllers issue as you.

**Comment by mahaarbo** [comment]
When you are running the visualization you are connecting to the IP `172.16.0.2`, but when you're running the joint position example controller you seem to be connecting to `171.16.0.2` was this the issue? That would explain the timeout.

**Comment by QingkaiLu** [comment]
> When you are running the visualization you are connecting to the IP `172.16.0.2`, but when you're running the joint position example controller you seem to be connecting to `171.16.0.2` was this the issue? That would explain the timeout.

That makes sense. That is a dumb mistake, sorry about that. I will test it on the robot again once I can work onsite.

**Comment by QingkaiLu** [comment]
> > When you are running the visualization you are connecting to the IP `172.16.0.2`, but when you're running the joint position example controller you seem to be connecting to `171.16.0.2` was this the issue? That would explain the timeout.
> 
> That makes sense. That is a dumb mistake, sorry about that. I will test it on the robot again once I can work onsite.

I tested the joint position controller example with the correct IP and it works now. Thank you for the help!
