### ISSUE TITLE
Update behaviour of /franka_control/set_EE_frame and FrankaState.msg for TCP changes in 0.8.0

### ISSUE THREAD

**Issue by smihael** [frankaemika/franka_ros#122]
According to https://github.com/frankaemika/libfranka/releases/tag/0.8.0, the behavior of `franka::Robot::setEE` has changed in libfranka. 

After upgrading the robot to latest firmware (Desk v4.0.4) and libfranka 0.8.0 (installed from ROS repositories for ROS melodic) from libfranka 0.7.1 brings following issues, when using  current version of `franka_ros` (0.7.1, installed from ROS repositories for ROS melodic)
- `F_T_NE` and `NE_T_EE` are not mapped to  [franka_msgs/FrankaState](https://github.com/frankaemika/franka_ros/blob/melodic-devel/franka_msgs/msg/FrankaState.msg)
-  /franka_control/set_EE_frame sets `NE_T_EE` instead of  `F_T_EE` (as expected from looking into [franka_msgs/SetEEFrame](https://github.com/frankaemika/franka_ros/blob/melodic-devel/franka_msgs/srv/SetEEFrame.srv)

Effectively, instead of changing  `F_T_EE` directly, set_EE_frame now adds `NE_T_EE`  to `F_T_EE`. 
Please reflect the changes of libfranka in the next franka_ros release and update ROS repository. Now the latest version of libfranka provided by `ros-melodic-libfranka` is 0.8.0, whereas the rest of `ros-melodic-franka_*`  is still at 0.7.1.

**Comment by sgabl** [comment]
Thanks for reporting, the correct mapping to `libfranka` 0.8.0 is now available in the develop branch.
