### ISSUE TITLE
could it achieve real-time control with franka_ros

### ISSUE THREAD

**Issue by yijionglin** [frankaemika/franka_ros#124]
Hi all,

I know with the `libfranka`, it could achieve [real-time control](https://frankaemika.github.io/docs/overview.html). I wonder if `franka_ros` could also achieve that (soft real-time safe is fine). If yes, what frequency could it achieve?

Any idea would be highly appreciated!

All the best,
Bourne

**Comment by sgabl** [comment]
Hi,

the same applies for `franka_ros`. As described [here](https://frankaemika.github.io/docs/overview.html), `franka_ros` integrates `libfranka` into ROS Control. Have a look at the `franka_ros` [examples](https://github.com/frankaemika/franka_ros/blob/kinetic-devel/franka_example_controllers/).
In general, the communication is done through TCP and UDP. Therefore only soft real-time is possible.
