### ISSUE TITLE
Gripper update rate at 10 Hz?

### ISSUE THREAD

**Issue by mahaarbo** [frankaemika/franka_ros#127]
https://github.com/frankaemika/franka_ros/blob/edba362bc216d7169f14801c92af70f4291a0f76/franka_gripper/src/franka_gripper_node.cpp#L158

In trying to port the code to ROS 2, I've noticed that the `franka_gripper_node.cpp` separates reading of the gripper from the main thread, and runs this at 10 Hz. Is there any reason for this?

**Comment by gollth** [comment]
Yes this is due to the internals of how the gripper works. BTW: there is an official ROS2 integration of franka_ros now: https://github.com/frankaemika/franka_ros2
