### ISSUE TITLE
Is there a way I can view commanded joint torques?

### ISSUE THREAD

**Issue by peasant98** [frankaemika/franka_ros#128]
Hi, 

Let's say I'm using a Velocity Joint Interface. Is there any way to the joint torques that end up getting sent to the robot?

Thanks!

**Comment by peasant98** [comment]
Any update on this @sgabl?

**Comment by sgabl** [comment]
Hi, yes you could just check [tau_J_d](https://frankaemika.github.io/libfranka/structfranka_1_1RobotState.html#a7086a89a2705810f93a3a95d43df2d9d) - there you see the desired link-side joint torque.

**Comment by peasant98** [comment]
Yes, but if I am running joint velocity control, I won't be able to see what's actually being sent.

**Comment by marcbone** [comment]
For velocity control there is no direct way to see the commanded torque. To do that you would have to write your own velocity controller on torque basis. However, you can still view the measured torques tau_J. This could be enough for some use-cases.
