### ISSUE TITLE
Publish joint states and control panda with Desk simultaneously 

### ISSUE THREAD

**Issue by ninafiona** [frankaemika/franka_ros#131]
I plan to control my panda using franka_control, but at the moment I use Desk. I want to record a bag file while executing my commands and started `roslaunch franka_visualization franka_visualization.launch robot_ip:=...` to publish my joint states. But when the franka_visualization node is running, I cannot start my task and get the error message in Desk: ''Robot service not connected to contoller.'' 

So my question: why does this behavior occur and is there another way of publishing my joint states that can run simultaneously with Desk?

(Ubuntu 20.04 - ROS noetic, libfranka 0.8.0)

**Comment by gollth** [comment]
Hi @ninafiona 

unfortunately it's not possible to use FCI and Desk at the same time. For more insight why this is the case refer to [system architecture in the tutorial paper](https://github.com/frankaemika/the_reference_platform#system-architecture) but to quote:

> Note that the FCI, the low-level 1 kHz interface to the robot bypasses the Franka Operating System and represents a direct UDP-based connection to the real-time robot control.

You have two options now:

1. Either you write a custom app with RIDE in which you write the joint states in the bag file yourself. For that check [this section in the tutorial paper](https://github.com/frankaemika/the_reference_platform/tree/main/2_RIDE#ride)
2. You port your Desk application to ROS control and use `franka_control` to run your controller. See our [FCI documentation](https://frankaemika.github.io/docs/franka_ros.html#franka-control) for how to integrate your controller and/or the [MoveIt](https://ros-planning.github.io/moveit_tutorials/) tutorial.

Hope this helps
