### ISSUE TITLE
how to set the SetFullCollisionBehavior?

### ISSUE THREAD

**Issue by xzhuzhu** [frankaemika/franka_ros#133]
In the process of interaction with the franka using my own controller, the "libfranka: Move command aborted: motion aborted by reflex! ["cartesian_reflex"]
control_command_success_rate: 1" 
error easily come. So how can I use the franka_msgs::SetFullCollisionBehavior?

**Comment by gollth** [comment]
Please refer to the [FCI-documentation](https://frankaemika.github.io/docs/libfranka.html#non-realtime-commands) and the [Doxygen documention](https://frankaemika.github.io/libfranka/classfranka_1_1Robot.html#a168e1214ac36d74ac64f894332b84534) of libfranka for how to use non realtime commands
