### ISSUE TITLE
Control Franka using Python

### ISSUE THREAD

**Issue by QingkaiLu** [frankaemika/franka_ros#140]
Hi, is it possible to control the Franka robot by publishing the desired robot state in ROS using python? Thank you!

**Comment by gollth** [comment]
Hi @QingkaiLu,

no this is not possible right now. Currently there is no (easy) way to use ros_control with python, but maybe [this discussion](https://answers.ros.org/question/295388/can-i-use-python-with-ros_control-package/?answer=295389#post-id-295389) provides you some points in the right direction.

I'd love to be proven wrong, but I have doubts that python is fast enough to fulfill the real time constraints, that the [FCI requires](https://frankaemika.github.io/docs/requirements.html). 

I will close this issue now, but please feel free to experiment and create a PR once you found a solution
