### ISSUE TITLE
Kinetic-devel branch catkin make 'ros_control' error

### ISSUE THREAD

**Issue by rickstaa** [frankaemika/franka_ros#141]
Just a quick heads up. The [kinetic-devel](https://github.com/frankaemika/franka_ros/tree/kinetic-devel) branch was not building on my system today. When running the `catkin_make` or `catkin build` commands, it give the following error even though the `ros-kinetic-ros-control` package is installed:

```bash
CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by "ros_control" with
  any of the following names:

    ros_controlConfig.cmake
    ros_control-config.cmake

  Add the installation prefix of "ros_control" to CMAKE_PREFIX_PATH or set
  "ros_control_DIR" to a directory containing one of the above files.  If
  "ros_control" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)
```

This is probably something related to my system but I put it here as a reference might other people also experience this problem.

# Work-arounds

## Checkout v0.5.0

As I only needed to perform some quick comparison between the ROS Noetic version and the Kinetic version is did not look into what causes this error. To solve my problem, I checked out the [v0.5.0](https://github.com/frankaemika/franka_ros/releases/tag/0.5.0) branch since it worked in the past. 

## Point catkin to the ros_control package

Another solution when you want to use the ros-kinetic branch is to use the following command:

```bash
catkin build -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=~/libfranka/build -Dros_control_DIR:PATH=/opt/ros/kinetic/share/ros_control
```

This points catkin to the ros_control package.

## SYstem info

**OS:** Ubuntu 16.0.4
**ROS version:** Kinetic
**Kernel:** 4.16.18-rt12
**Catkin_tools version:** 0.6.1
**Cmake version:** 3.5.1

**Comment by gollth** [comment]
Is this still a problem with the latest `kinetic-devel` aka. 0.8.0?

**Comment by rickstaa** [comment]
@gollth I performed some tests using [this singularity](https://github.com/rickstaa/real-panda-control-examples/blob/noetic-devel/real_panda_control_examples/containers/singularity/Singularity.panda_ros_kinetic) recipe and the kinetic branch now builds without any issues.
