### ISSUE TITLE
No Hand_arm.urdf.xacro file

### ISSUE THREAD

**Issue by MAnthrazit** [frankaemika/franka_ros#148]
Is there a reason why the hand_arm.urdf file was not included in the robot directory?

**Comment by gollth** [comment]
I assume you mean the `panda_arm_hand.xacro.urdf` file with `hand_arm.urdf`? We replaced it in 0.8.0 with an XACRO argument. Please see the [CHANGELOG](https://github.com/frankaemika/franka_ros/blob/noetic-devel/CHANGELOG.md#080---2021-08-03) or [this commit](https://github.com/frankaemika/franka_ros/commit/2dc885213c6a658a274146a1139ca1c4bfc93017) for more details
