### ISSUE TITLE
Grasp action behaviour

### ISSUE THREAD

**Issue by AndreaRoberti** [frankaemika/franka_ros#16]
Hi, 
i'm tryng to use the Grasp Action to grasp a simple cube (width 20mm, weight 300gr) . 
The gripper tries to grasp the cube, but as soon as it touches the object, it stops applying pressure and the cube is released .

e.g of parameters : 
width : 0.018 [m]
epsilon.inner = 0.005
epsilon.outer = 0.005
speed : 0.01  [m/s]
force: 10 [N]

I tried lots of parameters. 

Andrea

edit : was missing a 0 in width

**Comment by fwalch** [comment]
Did you try to set the width to 0.02m, i.e. the size of the cube?

**Comment by fwalch** [comment]
It sounds like there is a mismatch between the commanded width and the actual grasping width. Can you manually close the fingers around the object and check the gripper width (`gripper.readOnce().width` in libfranka's API)? If you use this value, grasping should be successful.

Note that what counts as a width of zero is determined by homing the gripper (`franka::Gripper::homing()`), so if you e.g. exchange the fingertips, you need to re-home.

**Comment by AndreaRoberti** [comment]
Thanks for fast reply, 
i did it what you suggest and now it's working , thanks!
