### ISSUE TITLE
[feature_request] Publish the 'joint_states_desired' topic in the gazebo simulation

### ISSUE THREAD

**Issue by rickstaa** [frankaemika/franka_ros#164]
It would be great if you could also publish the '/'. I think adding '/joint_states_desired' topic both in simulation and the real robot would improve translating between the two. I created pull request #145 for this.

Having #145 merged would allow for cleaner code while providing the gazebo simulation in the [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config) package. As a result, it is currently blocking the release of the ROS Noetic version of the [panda_moveit_config](https://github.com/rickstaa/panda_moveit_config/tree/noetic-devel-update) package.

**Comment by gollth** [comment]
I will close this as well, since we merged #145. Thanks again for your contribution
