### ISSUE TITLE
Small error in the pick & place documentation

### ISSUE THREAD

**Issue by rickstaa** [frankaemika/franka_ros#170]
Just a head-up, the command used in the https://frankaemika.github.io/docs/franka_ros.html#pick-place-example should be changed to. The RViz GUI is not loaded any more by default.

```bash
roslaunch franka_gazebo panda.launch x:=-0.5     world:=$(rospack find franka_gazebo)/world/stone.sdf    controller:=cartesian
_impedance_example_controller rviz:=true
```

**Comment by gollth** [comment]
Good catch. Added to the docs https://frankaemika.github.io/docs/franka_ros.html#franka-gazebo
