### ISSUE TITLE
`ns` parameter for `xacro:hand` is a misnomer

### ISSUE THREAD

**Issue by rhaschke** [frankaemika/franka_ros#185]
The `ns` parameter for `xacro:hand` isn't a (ROS) namespace, but simply a _name prefix_. I suggest renaming it, either to `prefix` or to `hand_id` - in line with `arm_id`.
https://github.com/frankaemika/franka_ros/blob/444748ec50827737affb40f219f9fdba39aa0404/franka_description/robots/hand.xacro#L4
https://github.com/frankaemika/franka_ros/blob/444748ec50827737affb40f219f9fdba39aa0404/franka_description/robots/hand.xacro#L12

**Comment by gollth** [comment]
I agree with you, that this is more a prefix than a namespace. However this `ns` parameter exists for a long time (since 0.2.0 or so) and is very stable. I don't think this justifies for such a breaking change in `hand.xacro`

**Comment by gavanderhoorn** [comment]
`xacro` supports default (values for) arguments, perhaps @rhaschke could add bw-compatibility?

**Comment by gollth** [comment]
That would help with the value provided for a parameter, if I understand you right @gavanderhoorn. But still any user code which instantiates the hand macro with a `ns` parameter would break, not?

**Comment by gavanderhoorn** [comment]
Not necessarily.

Just accept both, clearly mark `ns` as *deprecated* and forward values configured for `ns` to `prefix`.

**Comment by rhaschke** [comment]
It would be perfectly possible to print a deprecation message when `ns` is used and forward its value to `prefix`.
If you would like to have this kind of backwards compatibility, I can add corresponding code to #199, which is a thorough rework of the xacro URDF files. However, to my understanding `hand.xacro` is not exposed to the user, but only used "internally" in some `.urdf.xacro` files. For this reason, I didn't consider backwards compatibility for its macro parameters an important feature.
Let's discuss this in #199.

**Comment by gollth** [comment]
Its a public file, that anybody can use or include. That sounds not very "internally" to me.



> Just accept both, clearly mark `ns` as _deprecated_ and forward values configured for `ns` to `prefix`.

Good idea, @rhaschke could you sketch a solution in a separate PR, please? Let's not intermix stories into the #199
