### ISSUE TITLE
Failed to execute move_to_start .launch

### ISSUE THREAD

**Issue by MohammadKhatib** [frankaemika/franka_ros#19]
I have Franka Emika arm, I can move the arm and execute many launch files.
But many launch files demands running move_to_start.launch first, and I'm getting this problem once I launch move_to_start launch file:

[ERROR] [1529581739.667286319]: libfranka: Move command rejected: command not possible in the current mode!
================================================================================REQUIRED process [move_to_start-8] has died!
process has died [pid 7208, exit code 1, cmd /home/franka/catkin_ws/src/franka_ros/franka_example_controllers/scripts/move_to_start.py __name:=move_to_start __log:=/home/franka/.ros/log/150e77d0-7549-11e8-80f2-509a4c508bbf/move_to_start-8.log].
log file: /home/franka/.ros/log/150e77d0-7549-11e8-80f2-509a4c508bbf/move_to_start-8*.log
Initiating shutdown!

And also this warning and error:
[WARN] [1529581740.128126]: Controller Spawner error while taking down controllers: unable to connect to service: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[WARN] [1529581740.129442]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 104] Connection reset by peer
[move_group-7] escalating to SIGTERM

**Comment by sgabl** [comment]
Please open the external activation device before executing an example and recover from errors and reflexes which occurred before.

That can be done from an action client or by simply publishing on the action goal topic:
rostopic pub -1 /franka_control/error_recovery/goal franka_control/ErrorRecoveryActionGoal "{}"
