### ISSUE TITLE
[docs] Update franka_gazebo docs

### ISSUE THREAD

**Issue by rickstaa** [frankaemika/franka_ros#204]
You are probably aware of this issue, but I will add it since it is easily overlooked. The commands in the [franka-gazebo](https://frankaemika.github.io/docs/franka_ros.html#franka-gazebo) are not working anymore because the panda namespace was removed by default.

```bash
rostopic pub --once /panda/franka_gripper/move/goal franka_gripper/MoveActionGoal "goal: {width: 0.08, speed: 0.1}"
```

should be

```bash
rostopic pub --once /franka_gripper/move/goal franka_gripper/MoveActionGoal "goal: {width: 0.08, speed: 0.1}"
```

Similar for the grasp command.

**Comment by gollth** [comment]
Thanks for the reminder @rickstaa. The fix is already incorporated in the docs internally, and will be published to `https://frankaemika.github.io/` as soon as we release `franka_ros#develop` to `melodic-devel`/`noetic-devel`
