### ISSUE TITLE
Incorrect MoveIt! Joint Velocity Limits

### ISSUE THREAD

**Issue by davetcoleman** [frankaemika/franka_ros#21]
In [joint_limits.yaml](https://github.com/frankaemika/franka_ros/commit/9dd3086fea7f90525c6ff021ff537e7e7cad4012) I believe the velocity limits are off, e.g. Joint 0

According to the [Data Sheet](https://s3-eu-central-1.amazonaws.com/franka-de-uploads-staging/uploads/2018/05/2018-05-datasheet-panda.pdf) and the URDF Xacro these values should be 2.618

Which is the correct source of truth?

@fwalch @hmurraydavis

**Comment by krigi100** [comment]
I think the used velocity limits are in [panda_arm.xacro](https://github.com/frankaemika/franka_ros/blob/kinetic-devel/franka_description/robots/panda_arm.xacro), this are the same values mentioned in the [control parameters](https://frankaemika.github.io/docs/control_parameters.html) in the FCI-Documentation. Probably there are differences in the maximum velocities using the FCI and libfranka.

**Comment by fwalch** [comment]
The values in the [control parameters docu](https://frankaemika.github.io/docs/control_parameters.html) and the ones in the [current URDF](https://github.com/frankaemika/franka_ros/blob/kinetic-devel/franka_description/robots/panda_arm.xacro) should be the same. We indeed forgot to update the `joint_limits.yaml`, thanks for pointing that out!

I think the easiest solution would be to just set the `has_velocity_limits` flag to `false` to avoid such problems in the future. @davetcoleman Is there any disadvantage to this?

**Comment by davetcoleman** [comment]
No the ``joint_limits.yaml`` file is intended to override the URDF values if you want to lower the values for safety reasons. But if you just want them to be the same, yes I would disable them.

**Comment by fwalch** [comment]
We just released an update for franka_ros which fixes the joint velocity limits and also adds acceleration limits. We also had some wrong jerk and acceleration limits in `franka_hw`. As a result of these fixes, the robot moves much faster now when using MoveIt.
