### ISSUE TITLE
The 'panda_arm_hand.urdf.xacro' file is abscent in the franka_description folder, could you upload this file?

### ISSUE THREAD

**Issue by ksjz** [frankaemika/franka_ros#216]
when i learn the moveit tutorial (link:http://docs.ros.org/en/melodic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html), I found this file is abscent.  could you upload this file? thank you!

**Comment by ksjz** [comment]
ubuntu 18.04 + melodic

**Comment by gollth** [comment]
Hi @ksjz,

The `panda_arm_hand.urdf.xacro` was replaced in [0.8.0 by a XACRO argument](https://github.com/frankaemika/franka_ros/blob/8efef6235b969c68ec1f8d5bc85026e4bca9cf19/CHANGELOG.md?plain=1#L49). Use `panda_arm.urdf.xacro hand:=true` instead.

I suggest you open this ticket in the MoveIT Tutorials: https://github.com/ros-planning/moveit_tutorials
