### ISSUE TITLE
Errors by using MoveIt and Version 1.3.2

### ISSUE THREAD

**Issue by krigi100** [frankaemika/franka_ros#22]
Since I'm using Version 1.3.2 with libfranka 0.4.0 and franka_ros 0.5.0 sometimes an oscillation occurs by using the [move group interface tutorial ](https://github.com/ros-planning/moveit_tutorials/blob/kinetic-devel/doc/move_group_interface/src/move_group_interface_tutorial.cpp) with a real robot. Then the robot gets in an error like cartesian reflex or tauJ violation. 
With the older version I didn't had the problem. 
The error also occurs sometimes by planning and execute with MoveIt and the rviz gui.
Are the reason for the problem the changed rate limiters?
How can I fix the problem?.

**Comment by jrmout** [comment]
Yes, there are three reasons for that:
* The new version 1.3.2 disables by default the filters, so now the robot is following the raw signal that comes from the JointPositionTrajectoryController. 
* MoveIt! sends sometimes very small jumps that violate Panda's jerk limits. Those were filtered out by the filters before but they are now causing some trouble. 
* When several packet losses or a small jump occur the rate limiters try to keep the signals into the limits of the interface and that's what's making the robot unstable.

We are aware of this issue and we are working on a solution. As a quick fix you can try using the velocity controller by applying [this](https://github.com/frankaemika/franka_ros/files/2210078/moveit_velocity_control_diff.txt) diff. Let us know if it helps!

**Comment by krigi100** [comment]
Thanks a lot, 
with the velocity controller it works better, no oscillation occurs. But while working with `move_group.setMaxVelocityScalingFactor(1)` the robot crashes sometimes in virtual objects.
I will try to optimize the gains of the velocity controller.

**Comment by fwalch** [comment]
We just released a new version of libfranka and franka_ros, which should fix these problems. If you're still encountering problems, let us know and we'll reopen the issue!
