### ISSUE TITLE
Cannot edit Franka Panda in Solidworks Assembly

### ISSUE THREAD

**Issue by Jainil1729** [frankaemika/franka_ros#242]
I downloaded the step file of assembly from github and I want to edit it's gripper finger because in the real robot, I am using custom fingers. 
I basically want to do this so that I can export in urdf and then use moveit for the motion planning. 

Any help with this issue will be appreciated. Thanks!!

**Comment by gollth** [comment]
Hi @Jainil1729 

I'm not sure if I understand your problem. 

> I downloaded the step file of assembly from github

To my knowledge we have never pushed any Solidwork assemblies to Github. Can you provide a link please what you downloaded?

> I want to edit it's gripper finger

You could open the download the [franka_description/meshes/visual/finger.dae](https://github.com/frankaemika/franka_ros/blob/develop/franka_description/meshes/visual/finger.dae) and convert it to an STL file with a tool of your choice. We usually use [Blender](https://www.blender.org/) for this. Then you should be able to import and adjust the STL file. Save a polygon reduced version of it also to use for the collision model.

**Comment by gollth** [comment]
I assume you were able to solve the issue. Feel free to reopen if the issue persists
