### ISSUE TITLE
Get user button state

### ISSUE THREAD

**Issue by xav12358** [frankaemika/franka_ros#266]
Hello,

I want to catch user button interaction on the last joint. I know that we can collect the state of the robot_mode using FrankaState message.

Is there an other message to get the state of the button on the last joint?

**Comment by gollth** [comment]
Hi @xav12358 

The robot has many buttons at the pilot. Which one do you mean exactly?

**Comment by xav12358** [comment]
I mean these buttons.
![image](https://user-images.githubusercontent.com/12400238/177954690-cb919f5c-bfc6-4ff9-b1f0-94d6ea03f643.png)

**Comment by gollth** [comment]
The state of the pilot buttons cannot be accessed via the FCI. If you need them I suggest to use the App interface of our robot. Refer: https://github.com/frankaemika/the_reference_platform/tree/main/2_RIDE

Good luck!
