### ISSUE TITLE
Bugged runs for communication_test

### ISSUE THREAD

**Issue by aPonza** [frankaemika/franka_ros#29]
During my kernel testing in #23 I had 3 bugged runs (once with 4.4 twice with 4.13 out of 20 combined runs) of the communication test example of libfranka. They all gave a similar output, but I didn't find a consistent way of reproducing it. The output from the 4.4 run is:

<pre>
ap@ap-NUC7i7DNKE:~/git/libfranka/build$ ./examples/communication_test 172.16.2.101
WARNING: This example will move the robot! Please make sure to have the user stop button at hand!
Press Enter to continue...

Finished moving to initial joint configuration.

Starting communication test.
#100 Current success rate: 1.00
#200 Current success rate: 1.00
#300 Current success rate: 0.99
#400 Current success rate: 1.00
#500 Current success rate: 1.00
#600 Current success rate: 1.00
#700 Current success rate: 1.00
#800 Current success rate: 1.00
#900 Current success rate: 1.00
#1000 Current success rate: 1.00
#1100 Current success rate: 1.00
#1200 Current success rate: 1.00
#1300 Current success rate: 1.00
#1400 Current success rate: 1.00
#1500 Current success rate: 1.00
#1600 Current success rate: 0.98
#1700 Current success rate: 1.00
#1800 Current success rate: 1.00
#1900 Current success rate: 1.00
#2000 Current success rate: 1.00
#2100 Current success rate: 1.00
#2200 Current success rate: 1.00
#2300 Current success rate: 1.00
#2400 Current success rate: 1.00
#2500 Current success rate: 1.00
#2600 Current success rate: 0.98
#2700 Current success rate: 1.00
#2800 Current success rate: 1.00
#2900 Current success rate: 1.00
#3000 Current success rate: 1.00
#3100 Current success rate: 1.00
#3200 Current success rate: 1.00
#3300 Current success rate: 1.00
#3400 Current success rate: 1.00
#3500 Current success rate: 1.00
#3600 Current success rate: 0.98
#3700 Current success rate: 1.00
#3800 Current success rate: 1.00
#3900 Current success rate: 1.00
#4000 Current success rate: 1.00
#4100 Current success rate: 1.00
#4200 Current success rate: 1.00
#4300 Current success rate: 1.00
#4400 Current success rate: 1.00
#4500 Current success rate: 1.00
#4600 Current success rate: 1.00
#4700 Current success rate: 1.00
#4800 Current success rate: 1.00
#4900 Current success rate: 1.00
#5000 Current success rate: 1.00
#5100 Current success rate: 1.00
#5200 Current success rate: 1.00
#5300 Current success rate: 1.00
#5400 Current success rate: 1.00
#5500 Current success rate: 1.00
#5600 Current success rate: 1.00
#5700 Current success rate: 0.98
#5800 Current success rate: 0.96
#5900 Current success rate: 0.99
#6000 Current success rate: 0.98
#6100 Current success rate: 0.99
#6200 Current success rate: 1.00
#6300 Current success rate: 1.00
#6400 Current success rate: 1.00
#6500 Current success rate: 1.00
#6600 Current success rate: 1.00
#6700 Current success rate: 1.00
#6800 Current success rate: 1.00
#6900 Current success rate: 1.00
#7000 Current success rate: 1.00
#7100 Current success rate: 1.00
#7200 Current success rate: 1.00
#7300 Current success rate: 1.00
#7400 Current success rate: 1.00
#7500 Current success rate: 0.99
#7600 Current success rate: 1.00
#7700 Current success rate: 1.00
#7800 Current success rate: 1.00
#7900 Current success rate: 1.00
#8000 Current success rate: 0.98
#8100 Current success rate: 1.00
#8200 Current success rate: 1.00
#8300 Current success rate: 1.00
#8400 Current success rate: 1.00
#8500 Current success rate: 0.96
#8600 Current success rate: 1.00
#8700 Current success rate: 1.00
#8800 Current success rate: 1.00
#8900 Current success rate: 0.99
#9000 Current success rate: 1.00
#9100 Current success rate: 0.93
#9200 Current success rate: 0.93
#9300 Current success rate: 1.00
#9400 Current success rate: 1.00
#9500 Current success rate: 0.99
#9600 Current success rate: 1.00
#9700 Current success rate: 0.94
#9800 Current success rate: 0.99
#9900 Current success rate: 0.99
#10000 Current success rate: 1.00

Finished test, shutting down example

#######################################################
The control loop did not get executed <b>18446744073709551615</b> times in the
last 10000 milliseconds! (lost <b>18446744073709551615</b> robot states)

Control command success rate of <b>10001</b> samples: 
Max: 1.00
Avg: 1.00
Min: <b>0.90</b>
#######################################################
</pre>

As you can see there are a couple of issues:
- 10001 samples probably lead to an overflow/bad division which leads to the gigantic number of dropped states (which is likely very low instead);
- The listed minimum value is not actually present among the "Current success rate" output, and should probably be 0.93.

**Comment by sgabl** [comment]
Thanks for the feedback! We fixed the overflow/bad division bug in the next libfranka release! The example only prints every 100 cycles, however, the minimum success rate is calculated for every cycle. So there was one step of 10000 where you had a success rate of 0.9.
