### ISSUE TITLE
Strange external force and wrench from real robot

### ISSUE THREAD

**Issue by Lejou** [frankaemika/franka_ros#297]
Env: ROS Noetic

I start up the model_example_controller.launch in the terminal with a real robot and I obtained the weird F_ext with a large value on z. I think it has some relationship with the unmounted gripper, since when I run the simulation with gripper in gazebo, the F_ext is correct.

 Anyway, how to figure it? I really need a help.

![Screenshot from 2022-11-08 20-47-25](https://user-images.githubusercontent.com/33564160/200570013-f6f31df2-7cb7-429e-ac93-2ff78cfb6bd8.png)

**Comment by marcbone** [comment]
The robot still thinks you have a gripper attached. You will also feel that the robot will try to move up when you hand guide the robot. You have to go into settings in DESK (the webinterface) go to end-effector and set "None" as end-effector.

**Comment by Lejou** [comment]
Thank you for your help.
