### ISSUE TITLE
'Missing' install targets?

### ISSUE THREAD

**Issue by gavanderhoorn** [frankaemika/franka_ros#3]
Haven't checked all pkgs, but the `CMakeLists.txt` seem to be missing `install(..)` targets.

Is that on purpose or is it just an oversight?

**Comment by ch1bo** [comment]
Thanks for the notice. As I am not sure if ROS Bloom requires it to build the binary releases, it is possible that we just didn't needed them so far. Although system-level installs will be encouraged to be done via those released versions, we can surely add install statements if this is a use case you require?

**Comment by gavanderhoorn** [comment]
Bloom does no magic, so it will need install targets. Else your packages will be empty.
