### ISSUE TITLE
[franka_description] Docs say `gazebo=true` triggers use of paper's estimated paremters, but they are always used?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [frankaemika/franka_ros#300]
From docs:
https://github.com/frankaemika/docs/blame/12fb63aa406b3e33dfc57a97ad5a5362e1ad8aad/source/franka_ros.rst#L36-L39

However, upon inspection, it looks like the inertial parameters are *not* dependent on the `gazebo` parameters?
https://github.com/frankaemika/franka_ros/blob/a58d3052a241304392847df6464234c83d728a38/franka_description/robots/common/utils.xacro#L4-L6

Is this intended? If so, can the docs be updated?
If not, can this possibly be fixed?

Relates
https://github.com/frankaemika/franka_ros2/issues/11
https://www.franka-community.de/t/panda-dynamic-model/4573/3

**Comment by gollth** [comment]
Hi @EricCousineau-TRI

sorry for the late reply. The inertia parameters _are_ dependent on the `gazebo` arg but not in the place you searched for. Rather the condition is placed a little bit further down in the `link_with_sc` macro:

https://github.com/frankaemika/franka_ros/blob/2d458abad7390bb73771c91787c361c2b5cfa6ad/franka_description/robots/common/utils.xacro#L51-L53

You can also verify that by simply inspecting the URDFs ;)

```console
$ xacro $(rospack find franka_description)/robots/fr3/fr3.urdf.xacro | grep "<inertial>" | wc -l
0

$ xacro $(rospack find franka_description)/robots/fr3/fr3.urdf.xacro gazebo:=true | grep "<inertial>" | wc -l
8
```

I hope this answers your question. Feel free to reopen the ticket if not.

All the best
