### ISSUE TITLE
Incompatible library version

### ISSUE THREAD

**Issue by HukoOo** [frankaemika/franka_ros#310]
Hi,

I have installed franka libraries to Ubuntu 20.04, installed ROS Noetic and libfranka. 

When I try to launch in franka_control, I get the following error:
`[ERROR] [1671433188.939110450]: FrankaHW: Failed to initialize libfranka robot. libfranka: Incompatible library version (server version: 6, library version: 5). Please check https://frankaemika.github.io for Panda system updates or choose a libfranka version that uses the server version 6 from the table at https://frankaemika.github.io/docs/compatibility.html .`

version of libfranka and franka_ros are same with 0.10.0

and when I check version in the DESK, I can get following :
`Version 5.2.1  516a2e7aaa` 

What might be the problem?

Kind regards,
`

**Comment by marcbone** [comment]
You are not using libfranka 0.10.0 (then you would have library version 6). I guess you installed franka-ros over ROS, right? This will also install ros-noetic-libfranka which is version 0.9. I guess that this is shadowing your libfranka 0.10 version. You have to remove the other version of libfranka with "sudo apt remove ros-noetic-libfranka" and then compile franka_ros from source

**Comment by HukoOo** [comment]
The ros-noetic-libfranka and compiled libfranka were installed together.

I deleted  the noetic-libfranka and solved it.

Thank you.
