### ISSUE TITLE
Version 0.7.0: Missing installation of franka_control_services

### ISSUE THREAD

**Issue by rafaelrojasmiliani** [frankaemika/franka_ros#342]
In the cmake file of the the `franka_hw` package there is missing the installation command for the `franka_control_services` library. As a consequence, other packages cannot find this library after running catkin build with the following configuration
```
catkin config --install --install-space /opt/ros/${ROSDISTRO}/ --extend  /opt/ros/${ROSDISTRO}/ 
```

**Comment by andrejpan** [comment]
Due to limited resources, there will be no updates for older versions. Could you please use the latest release instead?

**Comment by rafaelrojasmiliani** [comment]
Ok. Thanks. Btw, I'm using this repo to [build customized docker images](https://github.com/rafaelrojasmiliani/franka_control_docker). Perhaps you could find that repo interesting.
