### ISSUE TITLE
Default impedance values

### ISSUE THREAD

**Issue by Marc-Morcos** [frankaemika/franka_ros#349]
Hi, I want to change the impedance values for cartesian_impedance (6 values) and joint_impedance (7 values) internal controllers. https://frankaemika.github.io/libfranka/classfranka_1_1Robot.html#aa18a28697cf6e3be16c6cff2dd839560

However, I don't know what the default values are, so I don't know what range to start in. Where can I find this information?

**Comment by marcbone** [comment]
You can find the default values [here](https://github.com/frankaemika/libfranka/blob/master/examples/examples_common.cpp#L12)

**Comment by Marc-Morcos** [comment]
Wow, these are high
