### ISSUE TITLE
Connect franka ros with Movegroup

### ISSUE THREAD

**Issue by saivojjala** [frankaemika/franka_ros#353]
Can someone please help me connect franka ros with movegroup. I would like to move my franka emika panda robot using the moveit plugin on rviz

**Comment by marcbone** [comment]
use the [panda_moveit_config](https://github.com/ros-planning/panda_moveit_config) and run
 `roslaunch panda_moveit_config franka_control.launch robot_ip:=<ip-of-your-robot>`

**Comment by saivojjala** [comment]
Does this interface require a real-time kernel? Is it at all possible to use the library with moveit without installing a different kernel. I tried installing the kernel but I get an error reading out of memory when i restart my laptop

**Comment by XuChen-AI** [comment]
> 使用[panda_moveit_config](https://github.com/ros-planning/panda_moveit_config)并运行 `roslaunch panda_moveit_config franka_control.launch robot_ip:=<ip-of-your-robot>`
Hi I'm using fr3, how can I modify panda_moveit_config to connect the moveit to the real robot arm? thank you!
