### ISSUE TITLE
How to code in eclipse

### ISSUE THREAD

**Issue by rachel-dev** [frankaemika/franka_ros#37]
Hi everyone,
I am new to use franka arm. I am wondering how to use eclipse to code for franka_controller like franka_example_controller.
I tried this solution:
in ~/catkin_ws
catkin_make --force-cmake -G"Eclipse CDT4 - Unix Makefiles"
it can't work.
But if I use moveit_tutorials from https://github.com/ros-planning/moveit_tutorials.git, it can work.
I think it misses libfranka. 
Another question: Can I use moveit to code for franka?
Thank you.
Rachel

**Comment by fwalch** [comment]
If you compiled libfranka from source, you need to specify `-DFranka_DIR:PATH=/path/to/libfranka/build` when invoking `catkin_make`. See also https://frankaemika.github.io/docs/installation.html#building-from-source
