### ISSUE TITLE
Some questions confuse me

### ISSUE THREAD

**Issue by itfanr** [frankaemika/franka_ros#38]
I read the source code of franka_ros and libfranka to learn ros. Now I have some questions:

1. franka_control is a node which directly communicate with robot?
2. libfranka and franka_control communicate with a customized tcp and udp ?
3.franka_control runs on robot controller machine and libfranka runs on a pc workstation?
4.If libfranka and franka_control communicate with a customized tcp and udp, but where the udp and tcp implemention? I didnot find the server.

Thank you!

**Comment by fwalch** [comment]
Both `libfranka` and `franka_ros` are running on your PC. The [documentation](https://frankaemika.github.io/docs/) has a detailed explanation of how the communication works. If the documentation still doesn't answer some of your questions, let us know :)

**Comment by itfanr** [comment]
But what  is  running on  robot ?

**Comment by fwalch** [comment]
> But what is running on robot ?

You can find some more details on that [here](https://frankaemika.github.io/docs/libfranka.html#under-the-hood).

**Comment by itfanr** [comment]
OK, I think there must  be EtherCAT driver level to drive the robot. Or, are there RTOS on robot? @fwalch

**Comment by fwalch** [comment]
The only way to control the robot with a low-level interface is via FCI, i.e. [libfranka](https://frankaemika.github.io/docs/libfranka.html)/franka_ros, from an external workstation PC. I can't give any information about what is running on the robot itself.

**Comment by itfanr** [comment]
@fwalch  ok, thank you very much.
