### ISSUE TITLE
Mesh appearance non-collision geometry

### ISSUE THREAD

**Issue by gavanderhoorn** [frankaemika/franka_ros#4]
This is not a complaint, but just curiosity: are you planning to release meshes other than STLs for the non-collision geometry? The robot is completely white in RViz for me at the moment, which is almost an offense to the aesthetics of the real robot.

Colladas with perhaps some texturing would be a huge improvement in visual appearance :)

**Comment by fwalch** [comment]
Thanks for the suggestion! We'll discuss this internally.

**Comment by gavanderhoorn** [comment]
Just a friendly 🛎 : have you guys made any progress with this?

The white is just too bright ;)

**Comment by fwalch** [comment]
Sorry it's taking so long, but I hope we'll soon have updated meshes in `franka_ros`. I'll leave a comment here when this has happened.

**Comment by fwalch** [comment]
With the new 0.3.0 release, we now have Collada meshes in `franka_description` :)
