### ISSUE TITLE
Why was panda_moveit_config move out?

### ISSUE THREAD

**Issue by rachel-dev** [frankaemika/franka_ros#42]
Why did you guys move panda_moveit_config out?

**Comment by fwalch** [comment]
From the README of https://github.com/ros-planning/panda_moveit_config:

> The Panda robot is the flagship MoveIt! integration robot used in the MoveIt! tutorials. Any changes to MoveIt! need to be propagated into this config fast, so this package is co-located under the ros-planning Github organization here.

Does that answer your question?

**Comment by rachel-dev** [comment]
I see. Thank you very much
