### ISSUE TITLE
Can I use ros-kinetic in docker for franka panda?

### ISSUE THREAD

**Issue by rachel-dev** [frankaemika/franka_ros#43]
Hi everyone,
Can I use ros kinetic in docker for franka panda? I also want to use moveit to plan path for the arm?
Is it possible?
Thank you at first.
Rachel

**Comment by fwalch** [comment]
Yes, it is possible to run libfranka/franka_ros inside Docker. For control/libfranka-based nodes, you need to set the `SYS_NICE` capability to allow setting the realtime thread priority, and use the "host" network mode to allow direct access to the network card connected to the robot.

**Comment by rachel-dev** [comment]
> Yes, it is possible to run libfranka/franka_ros inside Docker. For control/libfranka-based nodes, you need to set the `SYS_NICE` capability to allow setting the realtime thread priority, and use the "host" network mode to allow direct access to the network card connected to the robot.

How can I use moveit in docker to plan the path for robot arm?

**Comment by rachel-dev** [comment]
> Yes, it is possible to run libfranka/franka_ros inside Docker. For control/libfranka-based nodes, you need to set the `SYS_NICE` capability to allow setting the realtime thread priority, and use the "host" network mode to allow direct access to the network card connected to the robot.

Now I am using moveit in docker. Does it also require to work in the realtime?

**Comment by samarth-robo** [comment]
> Yes, it is possible to run libfranka/franka_ros inside Docker. For control/libfranka-based nodes, you need to set the `SYS_NICE` capability to allow setting the realtime thread priority, and use the "host" network mode to allow direct access to the network card connected to the robot.

@fwalch does the host need to be running a realtime kernel in this setup?

**Comment by faev999** [comment]
@samarth-robo  did you find an answer to your question?

**Comment by samarth-robo** [comment]
@faev999 I did not pursue the Docker path, sorry.
