### ISSUE TITLE
Panda C++ IK Solver?

### ISSUE THREAD

**Issue by davetcoleman** [frankaemika/franka_ros#45]
Does Franka Emika provide, or is anyone aware of, an IK solver we can use locally in our motion planning code, as opposed to hidden in Franka's control software? An customized/optimized IK solver for Panda would greatly speed up MoveIt! integrations and other control needs of our clients. Of course I already know about KDL and IKFast, but IKFast has issues working with Panda according to @mlautman.

Thanks!

**Comment by mlautman** [comment]
+1

**Comment by fwalch** [comment]
Unfortunately, we don't provide an IK solver.

**Comment by gavanderhoorn** [comment]
@fwalch wrote:
> Unfortunately, we don't provide an IK solver.

Is there a specific reason for that?

**Comment by jrmout** [comment]
@mlautman Could you elaborate on the issues of IKFast? Thanks!

**Comment by gavanderhoorn** [comment]
No comment from Franka Emika on this?
