### ISSUE TITLE
Virtual Wall requires more details

### ISSUE THREAD

**Issue by Adito5393** [frankaemika/franka_ros#46]
Could you provide more details on how to define the virtual wall? How does it work?

I tried setting the p_frame as an identity matrix (1 on diagonal, rest 0) and "object_world_size" set to x=0.6 y=0.3 z=0.5. I did not encounter any virtual wall while moving around the "object_world_size" position using the cartesian impedance controller example.
[Link API](https://frankaemika.github.io/libfranka/structfranka_1_1VirtualWallCuboid.html)

**Comment by fwalch** [comment]
This is indeed confusing. While FCI does provide a way to retrieve virtual walls, there is currently no possibility to configure such virtual walls on the system.

If you use `franka_ros`, maybe MoveIt functionality can help you out here: in [this example](https://ros-planning.github.io/moveit_tutorials/doc/move_group_interface/move_group_interface_tutorial.html#expected-output), an object is added to the workspace. MoveIt will plan motions accordingly and avoid collisions with this object.

**Comment by djl11** [comment]
Is there any plan to add this virtual wall feature? There is also research_interface:: robot::GetCartesianLimit defined in libfranka API, is this limit not functional in any way at the moment?

**Comment by sgabl** [comment]
At the moment we can not provide a time-frame for the virtual wall FCI implementation.
