### ISSUE TITLE
Publish rate of the franka_states does not go 1000Hz

### ISSUE THREAD

**Issue by bomarali** [frankaemika/franka_ros#51]
I have changed the publish rate from original 30Hz to 1000Hz in the default_controllers.yaml. 
But rostopic hz .../franka_states does not punch above 600Hz. 
I have only tested it on my laptop. Do you think I got a communication bottleneck?

**Comment by fwalch** [comment]
Sending data over a ROS publisher has a certain overhead, and I guess you are just hitting the limits there. You can create a custom ros_control controller (see e.g. `franka_control::FrankaStateController` or `franka_example_controllers` package) and process the data in its `update` function if you need to receive it with 1kHz.

**Comment by bomarali** [comment]
Yup that pushed it up.
