### ISSUE TITLE
pick and place sample task

### ISSUE THREAD

**Issue by amranov** [frankaemika/franka_ros#62]
hi guys ,
sorry my question is little weird since i am beginner 
i could run franka_example_control , and now i want to lean how to make a simple pick and place task using franka-ros

**Comment by fwalch** [comment]
You probably want to use [MoveIt](https://moveit.ros.org/), see the [pick and place tutorial](https://ros-planning.github.io/moveit_tutorials/doc/pick_place/pick_place_tutorial.html). For further franka_ros-related questions, you can use https://www.franka-community.de/. For MoveIt support, see https://moveit.ros.org/support/
