### ISSUE TITLE
Capture live date while moving with the native Programming interface

### ISSUE THREAD

**Issue by lorenz-halt** [frankaemika/franka_ros#64]
Hi, 
I want to log some data, such as forces and Cartesian Velocities of the tool, while the panda is moving according to a program that I created on the web desktop.
It would be convinient to log via ros topics but not manadory.

As far as I understood it, any roscontroller is blocking any other execution. Even if the roscontroller is only reading.

Is there any work around this issue? Is there a logging function within the web desktop toolbox that I can use?

Thank you for your advice.

**Comment by sgabl** [comment]
Hi, while the FCI is active, you can not use Desk and vice versa. However, we publish some data during desk execution like the robot configuration and robot status (have a look at the websockets), but not Cartesian velocities or forces.
