### ISSUE TITLE
can't recover from joint limit error

### ISSUE THREAD

**Issue by hironoriyh** [frankaemika/franka_ros#69]
Hi all,

 I can only recover from joint limit error via Desk and lock/unlock joints. 
Do you know how to recover from the error via publishing rostopic?

**Comment by aPonza** [comment]
```
rostopic pub -1 /franka_control/error_recovery/goal franka_control/ErrorRecoveryActionGoal "{}"
```

from [here](https://frankaemika.github.io/docs/franka_ros.html).

**Comment by hironoriyh** [comment]
I've tried publishing the message and could recover from most of errors except for joint limit error.

**Comment by aPonza** [comment]
Weird, it does take a while sometimes, but it always works for me. Are you sure it's not some other condition? Can you test if with only `franka_control` up and the robot in a `joint_position_limits_violation` with the EAD activated, publishing the message doesn't work?

**Comment by sgabl** [comment]
If this problem still persist, try publishing the topic to the `error_recovery` goal, download directly afterwards the logs of the robot and send it to `support@franka.de`.
