### ISSUE TITLE
franka_simulator

### ISSUE THREAD

**Issue by MaxBaeten** [frankaemika/franka_ros#7]
First of all: Great ROS support! 

Are there any plans to support simulation of a franka robot?
For example by providing a gazebo package containing a gazebo model of the robot? 
Or by adding a franka robot to the gazebo model database: http://www.gazebosim.org/tutorials?tut=model_contrib&cat=build_robot

**Comment by dudalu** [comment]
Thanks @MaxBaeten !

Unfortunately, at the moment there are no plans to provide a gazebo package.
