### ISSUE TITLE
JointImpedance and Moveit

### ISSUE THREAD

**Issue by PachisiHe** [frankaemika/franka_ros#73]
Hi,
I'm trying to move the Panda with Moveit and want to lower the Impedance-Value for a Peg-in-hole Problem. The Panda should move to the target_pose with lowered stiffness, so that he is fitting into the hole.

So i tried to lower the JointImpedance before calling the move_group to move with: 
std::string robot_ip = "172.16.0.2";
franka::Robot robot(robot_ip);
robot.setJointImpedance({{10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0}});

The Robot is now less stiff, move_group is planning the trajectory in Rviz, but the Robot is not moving, because of a timeout-Error:
[ERROR] [1563345807.811914063]: Controller is taking too long to execute trajectory (the expected upper bound for the trajectory execution was 6.489077 seconds). Stopping trajectory.

Is that the right way to lower the stiffness in combination with moveit?

Beside i found on FCI, that franka_control is offering a Service franka_control::SetJointImpedance, but i did not get a client call to work (catkin_make works, but at executing the stiffness is not lowered). 
Here is the part of my source code:
ros::ServiceClient joint_impedance = nh.serviceClient<franka_control::SetJointImpedance>("set_joint_impedance");
franka_control::SetJointImpedance impedance;
impedance.joint_stiffness = {{10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 10.0}};
joint_impedance.call(impedance);

Can you please help me?
Thank you in advance

**Comment by feimeng93** [comment]
Hi, have you dealt with this problem?
