### ISSUE TITLE
LIbfranka and Server Incompability

### ISSUE THREAD

**Issue by ceteke** [frankaemika/franka_ros#74]
Hi,

I have recently updated FCI to version 2.1.4, updated my OS to Ubuntu 18.04, installed ROS Melodic and libfranka (master branch). When I launch franka_control node from franka_ros it works, fine but when I try to launch franka_gripper node, I get the following error:

```
terminate called after throwing an instance of 'franka::IncompatibleVersionException'
  what():  libfranka: Incompatible library version (server version: 2, library version: 3). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.
```

As you can see, the exception states that libfranka and server versions are not compatible but as I said before both are up to date. 

What might be the problem?

Kind regards,

**Comment by sgabl** [comment]
For system updates compatible with libfranka >= 0.6.0 or the Schmalz Cobot Pump, please contact support. You already did that, so I'll close this issue here.

**Comment by M-A-Robson** [comment]
On a similar theme i am receiving the error:

```
terminate called after throwing an instance of 'franka::IncompatibleVersionException'
  what():  libfranka: Incompatible library version (server version: 4, library version: 3). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.
```

Is libfranka 0.8.0 not compatible with the current franka ros build? if so how do i regress the version on my robot? factory reset and reinstall an older software version?

**Comment by sgabl** [comment]
You can solve this issue by installing the newest `libfranka 0.8.0`, see [here](https://frankaemika.github.io/docs/installation_linux.html#building-from-source). Make sure that `franka_ros` uses `libfranka 0.8.0`.

**Comment by M-A-Robson** [comment]
I've tried to install from source the 0.8.0 version - ./examples/echo_robot_state works fine indicating that libfranka is good. However the source build of franka_ros fails when trying to use franka_control.launch with

```*** Error in `/home/mark.robson/catkin_ws/devel/lib/franka_control/franka_control_node': malloc(): memory corruption: 0x00000000010f8450 ***```

Ideally i would like to revert back my hardware to a working state (server version 3) until binaries are available through apt-get repository. is this possible?

edit: I should note that i've attempted a complete clean ros install and have only followed the instructions at the link provided in the previous comment to install both libfranka and franka_ros 

edit 2: i've created a new issue for the memory problem but would still like to know if its possible to revert the server to the older version #106

**Comment by sgabl** [comment]
I assume you use `franka_ros` develop branch? Can you try using `franka_ros` commit '406e118c143cbefb58c2db8b6a5da87345dd1949' (`git checkout 406e118c143cbefb58c2db8b6a5da87345dd1949`) or `franka_ros 0.6.0` and retest your example? Regarding downgrades, please contact support@franka.de for more information.

**Comment by M-A-Robson** [comment]
I'm getting the same memory allocation error with the ```git checkout 406e118c143cbefb58c2db8b6a5da87345dd1949``` commit also, franka_visualization works but not franka_control.

**Comment by savieee** [comment]
Hello 
I have installed libfranka 0.8.0 from the repository but still getting following error.

libfranka: Incompatible library version (server version: 3, library version: 4). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.

Please help and guide

**Comment by fwalch** [comment]
In this case, the libfranka version is newer than the robot version. You can either downgrade libfranka to 0.7.1 by [building from source](https://frankaemika.github.io/docs/installation_linux.html#building-from-source) or upgrade your robot's system version to version 4 (see https://frankaemika.github.io/).

**Comment by palaniappanvr** [comment]
Initially I had the error of
libfranka: Incompatible library version (server version: 3, library version: 4). Please check https://frankaemika.github.io for Panda system updates or use a different version of libfranka.
Then I tried to downgrade the libfranka version by removing libfranka(sudo apt remove) and then started building from source the version 0.7.1 (by got checkout 0.7.1). After cmake, now when I try to run rosrun libfranka echo_robot_state, the error is: package 'libfranka' not found.
Can anyone help me?

**Comment by marcbone** [comment]
libfranka is not a ros package, but a normal library. if you installed it with `sudo make install` inside the build folder, you can run `echo_robot_state <robot-ip>`

**Comment by M-A-Robson** [comment]
@marcbone  is correct you need franka_ros package to run with Ros. Libfranka is c++ library. Find out more about franka_ros here https://frankaemika.github.io/docs/franka_ros.html
