### ISSUE TITLE
catkin_make fails when installing

### ISSUE THREAD

**Issue by PakoYam** [frankaemika/franka_ros#75]
I am following this documentation[https://frankaemika.github.io/docs/installation_linux.html]() for installation in ROS Kinetic on Ubuntu 16.04.

After I run this command "catkin_make -DCMAKE_BUILD_TYPE=Release -DFranka_DIR:PATH=/path/to/libfranka/build", there is an error.

Base path: /home/vr-roboterprogrammierung/catkin_ws
Source space: /home/vr-roboterprogrammierung/catkin_ws/src
Build space: /home/vr-roboterprogrammierung/catkin_ws/build
Devel space: /home/vr-roboterprogrammierung/catkin_ws/devel
Install space: /home/vr-roboterprogrammierung/catkin_ws/install
####
####
-- Using CATKIN_DEVEL_PREFIX: /home/vr-roboterprogrammierung/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/kinetic
-- This workspace overlays: /opt/ros/kinetic
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/vr-roboterprogrammierung/catkin_ws/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.18
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 9 packages in topological order:
-- ~~  - franka_description
-- ~~  - franka_ros (metapackage)
-- ~~  - franka_msgs
-- ~~  - file_server
-- ~~  - franka_gripper
-- ~~  - franka_visualization
-- ~~  - franka_hw
-- ~~  - franka_control
-- ~~  - franka_example_controllers
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'franka_description'
-- ==> add_subdirectory(franka_ros/franka_description)
-- +++ processing catkin metapackage: 'franka_ros'
-- ==> add_subdirectory(franka_ros/franka_ros)
-- +++ processing catkin package: 'franka_msgs'
-- ==> add_subdirectory(franka_ros/franka_msgs)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- franka_msgs: 2 messages, 0 services
-- +++ processing catkin package: 'file_server'
-- ==> add_subdirectory(file_server)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- Generating .msg files for action file_server/FileTransferFromRos /home/vr-roboterprogrammierung/catkin_ws/src/file_server/action/FileTransferFromRos.action
-- file_server: 7 messages, 2 services
-- +++ processing catkin package: 'franka_gripper'
-- ==> add_subdirectory(franka_ros/franka_gripper)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at franka_ros/franka_gripper/CMakeLists.txt:17 (find_package):
  By not providing "FindFranka.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Franka", but
  CMake did not find one.

  Could not find a package configuration file provided by "Franka" (requested
  version 0.5.0) with any of the following names:

    FrankaConfig.cmake
    franka-config.cmake

  Add the installation prefix of "Franka" to CMAKE_PREFIX_PATH or set
  "Franka_DIR" to a directory containing one of the above files.  If "Franka"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/home/vr-roboterprogrammierung/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/vr-roboterprogrammierung/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

How could I solve this error? 
Thank you.

**Comment by fwalch** [comment]
`/path/to/libfranka/build` is a placeholder. You need to replace it with the actual path to the libfranka build directory.
