### ISSUE TITLE
Franka Gazebo Panda conversion for MuJoCo

### ISSUE THREAD

**Issue by melfm** [frankaemika/franka_ros#76]
Is it possible to load the franka panda model into the mujoco environment? MuJoCo can load XML model files in **MJCF** format, as well as **URDF** format.
The Gazebo models are described using `.dae` , `.xacro` files and `.stl` meshes. I was wondering if there's an easy way to convert these to URDF format. I already looked at collada_urdf package, but I think these two formats need to be combined?

Update : 
- I ended up using modified version of the URDF meshes from [here](https://github.com/StanfordASL/PandaRobot.jl) and then converted to MJCF,  and then loaded the model into the openai gym robotics environment.

**Comment by vipinpaul1990** [comment]
Hi, have you tried to convert Mujoco file to gazebo?
