### ISSUE TITLE
Could not load controller 'position_joint_trajectory_controller' because controller type 'position_controllers/JointTrajectoryController' does not exist.

### ISSUE THREAD

**Issue by trojantao** [frankaemika/franka_ros#83]
roslaunch franka_example_controllers move_to_start.launch robot_ip:=172.16.0.2
... logging to /home/trojan/.ros/log/4cb413c0-029c-11ea-9ce4-8c16458430ed/roslaunch-Y7000-4875.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Y7000:41443/

SUMMARY
========

PARAMETERS
 * /franka_control/arm_id: panda
 * /franka_control/cutoff_frequency: 100
 * /franka_control/internal_controller: joint_impedance
 * /franka_control/joint_names: ['panda_joint1', ...
 * /franka_control/rate_limiting: True
 * /franka_control/robot_ip: 172.16.0.2
 * /franka_state_controller/arm_id: panda
 * /franka_state_controller/joint_names: ['panda_joint1', ...
 * /franka_state_controller/publish_rate: 30
 * /franka_state_controller/type: franka_control/Fr...
 * /joint_state_desired_publisher/rate: 30
 * /joint_state_desired_publisher/source_list: ['franka_state_co...
 * /joint_state_publisher/rate: 30
 * /joint_state_publisher/source_list: ['franka_state_co...
 * /move_group/allow_trajectory_execution: True
 * /move_group/controller_list: [{'default': True...
 * /move_group/hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/jiggle_fraction: 0.05
 * /move_group/max_range: 5.0
 * /move_group/max_safe_path_cost: 1
 * /move_group/moveit_controller_manager: moveit_simple_con...
 * /move_group/moveit_manage_controllers: True
 * /move_group/octomap_frame: camera_rgb_optica...
 * /move_group/octomap_resolution: 0.05
 * /move_group/panda_arm/planner_configs: ['SBLkConfigDefau...
 * /move_group/panda_arm_hand/planner_configs: ['SBLkConfigDefau...
 * /move_group/planner_configs/BFMTkConfigDefault/balanced: 0
 * /move_group/planner_configs/BFMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/BFMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/BFMTkConfigDefault/heuristics: 1
 * /move_group/planner_configs/BFMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/BFMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/BFMTkConfigDefault/optimality: 1
 * /move_group/planner_configs/BFMTkConfigDefault/radius_multiplier: 1.0
 * /move_group/planner_configs/BFMTkConfigDefault/type: geometric::BFMT
 * /move_group/planner_configs/BKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/BKPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/BKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/BKPIECEkConfigDefault/type: geometric::BKPIECE
 * /move_group/planner_configs/BiESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiESTkConfigDefault/type: geometric::BiEST
 * /move_group/planner_configs/BiTRRTkConfigDefault/cost_threshold: 1e300
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_node_ratio: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/init_temperature: 100
 * /move_group/planner_configs/BiTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/BiTRRTkConfigDefault/temp_change_factor: 0.1
 * /move_group/planner_configs/BiTRRTkConfigDefault/type: geometric::BiTRRT
 * /move_group/planner_configs/ESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ESTkConfigDefault/type: geometric::EST
 * /move_group/planner_configs/FMTkConfigDefault/cache_cc: 1
 * /move_group/planner_configs/FMTkConfigDefault/extended_fmt: 1
 * /move_group/planner_configs/FMTkConfigDefault/heuristics: 0
 * /move_group/planner_configs/FMTkConfigDefault/nearest_k: 1
 * /move_group/planner_configs/FMTkConfigDefault/num_samples: 1000
 * /move_group/planner_configs/FMTkConfigDefault/radius_multiplier: 1.1
 * /move_group/planner_configs/FMTkConfigDefault/type: geometric::FMT
 * /move_group/planner_configs/KPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/KPIECEkConfigDefault/failed_expansion_score_factor: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/KPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/KPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/KPIECEkConfigDefault/type: geometric::KPIECE
 * /move_group/planner_configs/LBKPIECEkConfigDefault/border_fraction: 0.9
 * /move_group/planner_configs/LBKPIECEkConfigDefault/min_valid_path_fraction: 0.5
 * /move_group/planner_configs/LBKPIECEkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBKPIECEkConfigDefault/type: geometric::LBKPIECE
 * /move_group/planner_configs/LBTRRTkConfigDefault/epsilon: 0.4
 * /move_group/planner_configs/LBTRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/LBTRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/LBTRRTkConfigDefault/type: geometric::LBTRRT
 * /move_group/planner_configs/LazyPRMkConfigDefault/range: 0.0
 * /move_group/planner_configs/LazyPRMkConfigDefault/type: geometric::LazyPRM
 * /move_group/planner_configs/LazyPRMstarkConfigDefault/type: geometric::LazyPR...
 * /move_group/planner_configs/PDSTkConfigDefault/type: geometric::PDST
 * /move_group/planner_configs/PRMkConfigDefault/max_nearest_neighbors: 10
 * /move_group/planner_configs/PRMkConfigDefault/type: geometric::PRM
 * /move_group/planner_configs/PRMstarkConfigDefault/type: geometric::PRMstar
 * /move_group/planner_configs/ProjESTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/ProjESTkConfigDefault/range: 0.0
 * /move_group/planner_configs/ProjESTkConfigDefault/type: geometric::ProjEST
 * /move_group/planner_configs/RRTConnectkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTConnectkConfigDefault/type: geometric::RRTCon...
 * /move_group/planner_configs/RRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTkConfigDefault/type: geometric::RRT
 * /move_group/planner_configs/RRTstarkConfigDefault/delay_collision_checking: 1
 * /move_group/planner_configs/RRTstarkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/RRTstarkConfigDefault/range: 0.0
 * /move_group/planner_configs/RRTstarkConfigDefault/type: geometric::RRTstar
 * /move_group/planner_configs/SBLkConfigDefault/range: 0.0
 * /move_group/planner_configs/SBLkConfigDefault/type: geometric::SBL
 * /move_group/planner_configs/SPARSkConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARSkConfigDefault/max_failures: 1000
 * /move_group/planner_configs/SPARSkConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARSkConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARSkConfigDefault/type: geometric::SPARS
 * /move_group/planner_configs/SPARStwokConfigDefault/dense_delta_fraction: 0.001
 * /move_group/planner_configs/SPARStwokConfigDefault/max_failures: 5000
 * /move_group/planner_configs/SPARStwokConfigDefault/sparse_delta_fraction: 0.25
 * /move_group/planner_configs/SPARStwokConfigDefault/stretch_factor: 3.0
 * /move_group/planner_configs/SPARStwokConfigDefault/type: geometric::SPARStwo
 * /move_group/planner_configs/STRIDEkConfigDefault/degree: 16
 * /move_group/planner_configs/STRIDEkConfigDefault/estimated_dimension: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/STRIDEkConfigDefault/max_degree: 18
 * /move_group/planner_configs/STRIDEkConfigDefault/max_pts_per_leaf: 6
 * /move_group/planner_configs/STRIDEkConfigDefault/min_degree: 12
 * /move_group/planner_configs/STRIDEkConfigDefault/min_valid_path_fraction: 0.2
 * /move_group/planner_configs/STRIDEkConfigDefault/range: 0.0
 * /move_group/planner_configs/STRIDEkConfigDefault/type: geometric::STRIDE
 * /move_group/planner_configs/STRIDEkConfigDefault/use_projected_distance: 0
 * /move_group/planner_configs/TRRTkConfigDefault/frountierNodeRatio: 0.1
 * /move_group/planner_configs/TRRTkConfigDefault/frountier_threshold: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/goal_bias: 0.05
 * /move_group/planner_configs/TRRTkConfigDefault/init_temperature: 10e-6
 * /move_group/planner_configs/TRRTkConfigDefault/k_constant: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/max_states_failed: 10
 * /move_group/planner_configs/TRRTkConfigDefault/min_temperature: 10e-10
 * /move_group/planner_configs/TRRTkConfigDefault/range: 0.0
 * /move_group/planner_configs/TRRTkConfigDefault/temp_change_factor: 2.0
 * /move_group/planner_configs/TRRTkConfigDefault/type: geometric::TRRT
 * /move_group/planner_configs/TrajOptDefault/type: geometric::TrajOpt
 * /move_group/planning_plugin: ompl_interface/OM...
 * /move_group/planning_scene_monitor/publish_geometry_updates: True
 * /move_group/planning_scene_monitor/publish_planning_scene: True
 * /move_group/planning_scene_monitor/publish_state_updates: True
 * /move_group/planning_scene_monitor/publish_transforms_updates: True
 * /move_group/request_adapters: default_planner_r...
 * /move_group/sensors: [{'point_subsampl...
 * /move_group/start_state_max_bounds_error: 0.1
 * /move_group/trajectory_execution/allowed_execution_duration_scaling: 1.2
 * /move_group/trajectory_execution/allowed_goal_duration_margin: 0.5
 * /move_group/trajectory_execution/allowed_start_tolerance: 0.01
 * /position_joint_trajectory_controller/constraints/goal_time: 0.5
 * /position_joint_trajectory_controller/constraints/panda_joint1/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint2/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint3/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint4/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint5/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint6/goal: 0.05
 * /position_joint_trajectory_controller/constraints/panda_joint7/goal: 0.05
 * /position_joint_trajectory_controller/joints: ['panda_joint1', ...
 * /position_joint_trajectory_controller/type: position_controll...
 * /robot_description: <?xml version="1....
 * /robot_description_kinematics/panda_arm/kinematics_solver: kdl_kinematics_pl...
 * /robot_description_kinematics/panda_arm/kinematics_solver_search_resolution: 0.005
 * /robot_description_kinematics/panda_arm/kinematics_solver_timeout: 0.05
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint1/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_acceleration_limits: False
 * /robot_description_planning/joint_limits/panda_finger_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_acceleration: 0
 * /robot_description_planning/joint_limits/panda_finger_joint2/max_velocity: 0.1
 * /robot_description_planning/joint_limits/panda_joint1/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint1/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint1/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint2/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint2/max_acceleration: 1.875
 * /robot_description_planning/joint_limits/panda_joint2/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint3/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint3/max_acceleration: 2.5
 * /robot_description_planning/joint_limits/panda_joint3/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint4/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint4/max_acceleration: 3.125
 * /robot_description_planning/joint_limits/panda_joint4/max_velocity: 2.175
 * /robot_description_planning/joint_limits/panda_joint5/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint5/max_acceleration: 3.75
 * /robot_description_planning/joint_limits/panda_joint5/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint6/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint6/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint6/max_velocity: 2.61
 * /robot_description_planning/joint_limits/panda_joint7/has_acceleration_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/has_velocity_limits: True
 * /robot_description_planning/joint_limits/panda_joint7/max_acceleration: 5
 * /robot_description_planning/joint_limits/panda_joint7/max_velocity: 2.61
 * /robot_description_semantic: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    controller_spawner (controller_manager/spawner)
    franka_control (franka_control/franka_control_node)
    joint_state_desired_publisher (joint_state_publisher/joint_state_publisher)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    move_group (moveit_ros_move_group/move_group)
    move_to_start (franka_example_controllers/move_to_start.py)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    state_controller_spawner (controller_manager/spawner)

auto-starting new master
process[master]: started with pid [4892]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 4cb413c0-029c-11ea-9ce4-8c16458430ed
process[rosout-1]: started with pid [4905]
started core service [/rosout]
process[franka_control-2]: started with pid [4908]
process[state_controller_spawner-3]: started with pid [4909]
process[robot_state_publisher-4]: started with pid [4910]
process[joint_state_publisher-5]: started with pid [4911]
process[joint_state_desired_publisher-6]: started with pid [4912]
process[controller_spawner-7]: started with pid [4915]
process[move_group-8]: started with pid [4916]
process[move_to_start-9]: started with pid [4917]
**INFO: cannot create a symlink to latest log directory: [Errno 2] No such file or directory: '/home/trojan/.ros/log/latest'**
[INFO] [1573268094.926737]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1573268094.928980]: Controller Spawner: Waiting for service controller_manager/load_controller
[INFO] [1573268095.845092]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1573268095.846820]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1573268095.849880]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1573268095.851530]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1573268095.854420]: Loading controller: franka_state_controller
[INFO] [1573268095.856722]: Loading controller: position_joint_trajectory_controller
**[INFO] [1573268095.971015]: Controller Spawner: Loaded controllers: franka_state_controller
[ERROR] [1573268095.973288636]: Could not load controller 'position_joint_trajectory_controller' because controller type 'position_controllers/JointTrajectoryController' does not exist.
[ERROR] [1573268095.973496950]: Use 'rosservice call controller_manager/list_controller_types' to get the available types**
[INFO] [1573268095.982690]: Started controllers: franka_state_controller
[ERROR] [1573268096.975759]: Failed to load position_joint_trajectory_controller
[INFO] [1573268096.976908]: Controller Spawner: Loaded controllers: 
[INFO] [1573268096.983291]: Started controllers: 
[ INFO] [1573268098.903892205]: Loading robot model 'panda'...
[ INFO] [1573268099.766778216]: Loading robot model 'panda'...
[ INFO] [1573268100.021251247]: Publishing maintained planning scene on 'monitored_planning_scene'
[ INFO] [1573268100.025564175]: MoveGroup debug mode is OFF
Starting context monitors...
[ INFO] [1573268100.025628206]: Starting scene monitor
[ INFO] [1573268100.029611636]: Listening to '/planning_scene'
[ INFO] [1573268100.029654509]: Starting world geometry monitor
[ INFO] [1573268100.033884804]: Listening to '/collision_object' using message notifier with target frame '/world '
[ INFO] [1573268100.038583686]: Listening to '/planning_scene_world' for planning scene world geometry
[ INFO] [1573268100.457441280]: Listening to '/camera/depth_registered/points' using message filter with target frame '/world '
[ INFO] [1573268100.470910645]: Listening to '/attached_collision_object' for attached collision objects
Context monitors started.
[ WARN] [1573268100.495079772]: Unable to update multi-DOF joint 'virtual_joint': TF has no common time between '/world' and 'panda_link0': 
[ INFO] [1573268101.211322096]: Initializing OMPL interface using ROS parameters
[ INFO] [1573268101.269996895]: Using planning interface 'OMPL'
[ INFO] [1573268101.335328403]: Param 'default_workspace_bounds' was not set. Using default value: 10
[ INFO] [1573268101.338085142]: Param 'start_state_max_bounds_error' was set to 0.1
[ INFO] [1573268101.340402044]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1573268101.342683241]: Param 'start_state_max_dt' was not set. Using default value: 0.5
[ INFO] [1573268101.344744578]: Param 'jiggle_fraction' was set to 0.05
[ INFO] [1573268101.346772931]: Param 'max_sampling_attempts' was not set. Using default value: 100
[ INFO] [1573268101.347024857]: Using planning request adapter 'Add Time Parameterization'
[ INFO] [1573268101.347119248]: Using planning request adapter 'Fix Workspace Bounds'
[ INFO] [1573268101.347196112]: Using planning request adapter 'Fix Start State Bounds'
[ INFO] [1573268101.347279716]: Using planning request adapter 'Fix Start State In Collision'
[ INFO] [1573268101.347360005]: Using planning request adapter 'Fix Start State Path Constraints'
INFO: cannot create a symlink to latest log directory: [Errno 17] File exists
[ WARN] [1573268102.007522209]: The complete state of the robot is not yet known.  Missing virtual_joint
Failed to import pyassimp, see https://github.com/ros-planning/moveit/issues/86 for more info
[ WARN] [1573268106.407716123]: Waiting for position_joint_trajectory_controller/follow_joint_trajectory to come up
[ WARN] [1573268112.408133870]: Waiting for position_joint_trajectory_controller/follow_joint_trajectory to come up
[ERROR] [1573268118.408627558]: Action client not connected: position_joint_trajectory_controller/follow_joint_trajectory
[ INFO] [1573268118.432836568]: Returned 0 controllers in list
[ INFO] [1573268118.510401739]: Trajectory execution is managing controllers
Loading 'move_group/ApplyPlanningSceneService'...
Loading 'move_group/ClearOctomapService'...
Loading 'move_group/MoveGroupCartesianPathService'...
Loading 'move_group/MoveGroupExecuteTrajectoryAction'...
Loading 'move_group/MoveGroupGetPlanningSceneService'...
Loading 'move_group/MoveGroupKinematicsService'...
Loading 'move_group/MoveGroupMoveAction'...
Loading 'move_group/MoveGroupPickPlaceAction'...
[ INFO] [1573268118.905285676]: Loading robot model 'panda'...
Loading 'move_group/MoveGroupPlanService'...
Loading 'move_group/MoveGroupQueryPlannersService'...
Loading 'move_group/MoveGroupStateValidationService'...
[ INFO] [1573268118.955043580]: 

********************************************************
* MoveGroup using: 
*     - ApplyPlanningSceneService
*     - ClearOctomapService
*     - CartesianPathService
*     - ExecuteTrajectoryAction
*     - GetPlanningSceneService
*     - KinematicsService
*     - MoveAction
*     - PickPlaceAction
*     - MotionPlanService
*     - QueryPlannersService
*     - StateValidationService
********************************************************

[ INFO] [1573268118.955263298]: MoveGroup context using planning plugin ompl_interface/OMPLPlanner
[ INFO] [1573268118.955303188]: MoveGroup context initialization complete

You can start planning now!

[ INFO] [1573268119.013124726]: Loading robot model 'panda'...
[ INFO] [1573268120.106990137]: Ready to take commands for planning group panda_arm.
[ WARN] [1573268120.141483390]: No transform available between frame 'panda_EE' and planning frame '/world' ()
[ WARN] [1573268120.141598647]: No transform available between frame 'panda_K' and planning frame '/world' ()
[ INFO] [1573268120.142006523]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1573268120.142679358]: Planning attempt 1 of at most 1
[ INFO] [1573268120.203677167]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1573268120.229585784]: RRTConnect: Starting planning with 1 states already in datastructure
[ INFO] [1573268120.235870590]: RRTConnect: Created 5 states (2 start + 3 goal)
[ INFO] [1573268120.236028361]: Solution found in 0.006879 seconds
[ INFO] [1573268120.243249873]: SimpleSetup: Path simplification took 0.006840 seconds and changed from 4 to 2 states
[ INFO] [1573268120.245273572]: Returned 0 controllers in list
[ERROR] [1573268120.245444769]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
[ERROR] [1573268120.245552921]: Known controllers and their joints:

[ERROR] [1573268120.245799224]: Apparently trajectory initialization failed
[ INFO] [1573268120.246729112]: ABORTED: Solution found but controller failed during execution
================================================================================REQUIRED process [move_to_start-9] has died!
process has finished cleanly
log file: /home/trojan/.ros/log/4cb413c0-029c-11ea-9ce4-8c16458430ed/move_to_start-9*.log
Initiating shutdown!
================================================================================
[move_to_start-9] killing on exit
[move_group-8] killing on exit
[joint_state_desired_publisher-6] killing on exit
[controller_spawner-7] killing on exit
[joint_state_publisher-5] killing on exit
[robot_state_publisher-4] killing on exit
[state_controller_spawner-3] killing on exit
[franka_control-2] killing on exit
[INFO] [1573268121.357164]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1573268121.358378]: Stopping all controllers...
[INFO] [1573268121.364873]: Shutting down spawner. Stopping and unloading controllers...
[INFO] [1573268121.366201]: Stopping all controllers...
[WARN] [1573268121.422813]: Controller Spawner error while taking down controllers: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] [1573268121.512119]: Controller Spawner error while taking down controllers: unable to connect to service: [Errno 104] Connection reset by peer
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by trojantao** [comment]
when i want to use the demo flaunch  move_to_start.launch meet the error

**Comment by trannguyenle95** [comment]
I think the error occurs because you don't have JointTrajectoryController. The same problem and solution are addressed [here]( https://answers.ros.org/question/254084/gazebo-could-not-load-controller-jointtrajectorycontroller-does-not-exist-mastering-ros-chapter-10/).

**Comment by gollth** [comment]
Hi @trojantao it looks like you have no controller running, which can execute a position trajectory:

```
[ INFO] [1573268120.245273572]: Returned 0 controllers in list
[ERROR] [1573268120.245444769]: Unable to identify any set of controllers that can actuate the specified joints: [ panda_joint1 panda_joint2 panda_joint3 panda_joint4 panda_joint5 panda_joint6 panda_joint7 ]
```

Like @trannguyenle95 suggested, installing the controller might help in your setup. I'll close this ticket, but feel free to reopen if the issue persists.

P.S: Please format your logs in code blocks next time for better readability
