### ISSUE TITLE
Questions regarding link length

### ISSUE THREAD

**Issue by ghost** [frankaemika/franka_ros#92]
Hi all,

I wonder if anyone knows the linkage length for the Emika Panda? I know its DH parameters as listed [here](https://frankaemika.github.io/docs/control_parameters.html). However, I'm not able to find its linkage length. For example, when we look at the plot as shown in the above link, what would be the length from the 2nd revolute joint to the 3rd revolute joint?

**Comment by gollth** [comment]
You can get an approximation of this by opening the [visual mesh files](https://github.com/frankaemika/franka_ros/tree/develop/franka_description/meshes/visual) in your favorite 3D Modelling software and measure them there. I will close this ticket in the hope this answers your question. If not feel free to reopen
